{48}{105}Previously on "Buffy the Vampire Slayer":
{138}{218}- I'm Faith.|- I'd say there was a new slayer in town.
{258}{306}She's unstable, Buffy.
{333}{358}Faith, no.
{363}{413}- You killed a man,|- I don't care,
{423}{484}No one can stop the Ascension,|Mayor's got it wired, B,
{498}{584}He built this town for demons to feed on.|Come Graduation Day, he's gettin' paid.
{603}{671}- Open your present.|- This is a thing of beauty, boss,
{678}{712}No.
{723}{777}Faith?
{918}{976}I'm leaving - after the Ascension.
{1008}{1051}You don't wanna be with me?
{1098}{1134}I don't.
{1188}{1262}I can't believe you're breaking up with me.
{1443}{1488}OK. Thanks a lot.
{1503}{1594}I can't believe this loser look.|I lobbied so hard for the teal.
{1608}{1654}No one ever listens to me.
{1668}{1728}Lone fashionable wolf.
{1728}{1781}I like the maroon. It has more dignity.
{1803}{1894}Dignity? You? In relation to clothes?|I'm awash in a sea of confusion.
{1908}{2003}I just wanna look respectable in this.|Considering I'm probably gonna die in it.
{2028}{2075}- Excuse me?|- I'm telling ya.
{2088}{2160}I woke up the other day with|this feeling in my gut. I just know:
{2163}{2226}there is no way|I'm getting out of this school alive.
{2238}{2307}Wow. You've really mastered|the power of positive giving up.
{2328}{2430}I've been lucky too many times.|My number's comin' up. And I was short.
{2463}{2516}One more rotation, and I'm shippin' stateside.
{2523}{2591}- You know what I mean?|- Seldom, if ever.
{2718}{2772}Bye. We'll keep in touch.
{2778}{2877}- Willow, will you sign my yearbook?|- Yeah. You have to sign mine, too.
{3003}{3077}You know, I really wish|we'd got to know each other better.
{3093}{3170}- Me, too.|- I mean, you're so smart.
{3183}{3260}- I always wanted to be like that.|- Thanks. You're so sweet.
{3333}{3386}- I hope we don't lose touch.|- No. We'll hang out.
{3393}{3432}- Bye.|- Bye.
{3438}{3508}- Oh, I'm gonna miss her.|- Don't you hate her?
{3513}{3599}Yes, with a fiery vengeance.|She picked on me for ten years.
{3618}{3670}The vacuous tramp.
{3678}{3757}It's like a sickness, Buffy.|I'm just missing everything.
{3768}{3846}- I miss PE.|- I think it's contagious.
{3888}{3973}The whole senior class|has turned into the sixties,
{3993}{4056}or what I imagine|the sixties would have been like,
{4068}{4116}without the war and the hairy armpits.
{4128}{4199}- You don't feel it?|- No, I don't.
{4203}{4335}I mean, I guess I'll miss stuff, but|I just don't get the whole graduation thing.
{4353}{4408}You get a piece of paper,|and nothing changes.
{4428}{4485}I don't even think I'm gonna go.
{4488}{4544}Oh, trusty soda machine.
{4563}{4617}I push you for root beer, you give me Coke.
{4683}{4750}What do you mean, not go? Why not?
{4758}{4847}Ascension. Mayor becoming a demon,|snacking upon populace.
{4863}{4925}- I was planning on fighting him.|- You can't do both?
{4938}{4988}Both what?
{4998}{5052}Go to graduation, and fight the Mayor.
{5058}{5131}The Mayor? What, you guys didn't hear?
{5148}{5204}- Hear what?|- Who our commencement speaker is.
{5223}{5253}- Siegfried?|- No.
{5253}{5344}- Roy? One of the tigers?|- No. Come out of the fantasy, Will.
{5358}{5406}I don't believe this.
{5418}{5481}Lends credence to my|"I'm gonna die" theorem, doesn't it?
{5493}{5568}Mayor at graduation.|100 helpless kids to feed on.
{5598}{5642}You got any other surprises for us?
{5793}{5841}Just a moment.
{5958}{6030}- Hi. I'm looking for Professor Worth.|- That's me.
{6033}{6093}But I should ask you|to come back during office hours.
{6108}{6165}- Students generally...|- I'm not from the college.
{6168}{6230}I work for Mayor Wilkins. I'm Faith.
{6243}{6290}Well, come in. Please.
{6333}{6391}I was so surprised when he called.
{6423}{6501}I didn't expect a politician|to be interested in my research.
{6513}{6588}- He's a big fan, Professor.|- Lester's fine.
{6633}{6686}Are we alone here, Lester?
{6693}{6735}Well, yes.
{6768}{6825}Lifelong bachelor.
{6843}{6903}- I like my space.|- I hear that.
{6903}{6956}You wanna turn and face the wall, Lester?
{6978}{7053}- What are you doing?|- I'll make it quick.
{7083}{7137}Put that away.
{7158}{7201}- I'll scream.|- Who wouldn't?
{7248}{7324}- Please.|- Sorry, friend. Boss wants you dead.
{7353}{7430}- Why?|- You know, I never thought to ask.
{8944}{8995}And everything went|smoothly with Mr Worth?
{9004}{9056}Not if you're Mr Worth.
{9094}{9138}Well, that's swell.
{9154}{9211}You know how I feel about loose ends.
{9244}{9339}And the big day is so close,|you can smell the excitement in the air.
{9394}{9448}Say, are you ever coming out of there?
{9454}{9507}- I don't know.|- Come on.
{9709}{9782}Wow. Aren't you a vision!
{9814}{9871}I feel wicked stupid in this.
{9904}{9966}You look lovely. Perfect for the Ascension.
{9994}{10078}Any boys that manage to survive|will be lining up to ask you out.
{10084}{10130}It just isn't me, though.
{10144}{10171}Not you?
{10204}{10257}Let me tell you something.
{10264}{10310}Nobody knows what you are.
{10354}{10408}Not even you, Little Miss Seen It All.
{10459}{10510}The Ascension isn't just my day.
{10519}{10626}It's yours, too. Your day to blossom, show|the world what a powerful girl you are.
{10669}{10763}When I think of what you've done,|what I know you will do...
{10849}{10902}No father could be prouder.
{10969}{11026}- I hope I don't let you down.|- Impossible.
{11059}{11164}Now, come on. Change back into|your street clothes. I'll buy you an icy.
{11474}{11532}- Hey, Rosenberg.|- Hey, Percy.
{11534}{11594}Check it out. History final.
{11639}{11712}- B minus. That's great.|- I'm a scholar. I'm, like, a scholar.
{11714}{11760}- Congratulations.|- Hey, listen.
{11789}{11844}Thank you. I mean, for helping me.
{11864}{11974}Being so patient. And also for not|kicking my ass like you did in the Bronze.
{11999}{12097}You know, Percy, that was|actually for your own good.
{12134}{12178}I know, I know.
{12179}{12226}- Hey.|- Hey.
{12239}{12316}- History's important, you know.|- No, I totally get that now.
{12329}{12390}And I got the grades,|and I'm graduating tomorrow.
{12404}{12457}I can forget all this crap.
{12509}{12586}Well, after graduation, he may not|have the chance to forget it all.
{12644}{12688}I'm just trying to keep things light.
{12704}{12795}But things aren't light. I mean, it's|bad enough we have to fight the Mayor.
{12809}{12876}I don't want him|eating Percy and the whole class.
{12884}{12968}We have to find a spell or something|to stop the Ascension.
{12989}{13042}Then we will.
{13199}{13247}Thank you for joining us, Mr Harris.
{13274}{13391}Look, I realise you've all finished your finals|and you're ready to move on.
{13409}{13469}But you haven't graduated yet.
{13484}{13563}This is still a class,|and everyone will participate.
{13604}{13654}Mr Harris, would you care to begin?
{13784}{13830}- E,|- No.
{13859}{13904}There's no E,
{13904}{13978}They always go for the E,
{14054}{14098}- Next...|- Hi.
{14114}{14160}- Steven.|- Hey.
{14189}{14229}- L ?|- So I was wondering...
{14249}{14384}Maybe if you're free this weekend,|maybe we could do some entertaining thing.
{14414}{14497}Would that be you telling me about|the men you destroyed in your demon days?
{14519}{14572}Cos pencil me in.
{14624}{14709}Well, we could do something else you like.|We could...
{14774}{14829}watch sports of some kind.
{14879}{14958}- I don't know.|- Men like sports. I'm sure of it.
{15014}{15071}Yes. Men like sports.
{15074}{15174}Men watch the action movie. They eat of|the beef, and enjoy to look at the bosoms.
{15194}{15259}A thousand years,|and that's all you've learned?
{15269}{15348}Hey, I'm trying, OK?|You don't need to take my head off.
{15404}{15461}I'm sorry.
{15464}{15513}Look...
{15539}{15603}I don't even know if|I'm gonna make it to next weekend.
{15614}{15670}Tell you what, I survive the Ascension,
{15674}{15760}then maybe you and I|could do some sports-related...
{15809}{15834}What?
{15843}{15904}- Faith.|- You're sure?
{15933}{16010}It's one of her pieces.|I recognise the brushwork.
{16083}{16190}"Brutally stabbed. Lester Worth,|visiting professor of geology."
{16218}{16284}There's nothing in here|that bellows "motive".
{16293}{16346}Random killing, perhaps? Fit of rage?
{16353}{16455}Everybody does seem to be going a bit mad,|and Faith has something of a head start.
{16473}{16528}Doesn't read. I think it's homework.
{16548}{16641}- The Mayor wanted him out of the way.|- Which leads to the question "How come?"
{16653}{16729}I'm gonna destroy the entire city,|but I kill harmless Lester first?
{16743}{16838}Tying up loose ends?|Lester had something, or knew something.
{16848}{16935}And I wanna know too. The Mayor's|trying to hide. I say we go seek.
{16983}{17035}By attempting to keep|a valuable clue from us,
{17043}{17126}the Mayor may have|inadvertently led us right to it.
{17163}{17230}What page are you on, Wes?|Cos we already got there.
{17253}{17298}Yes. Well...
{17298}{17398}You will go tonight, look over his apartment.|Anything of note, report back here.
{17418}{17479}I just love it|when you take charge, you man, you.
{17508}{17553}That... Was that a yes?
{17553}{17624}- I'm having trouble keeping track.|- I'll go.
{17658}{17710}Be careful. If Faith should show up...
{17718}{17811}I don't think she'll show. Been there,|killed that. She's not much for follow-up.
{17823}{17907}Nonetheless, keep watch.|Faith has you at a disadvantage, Buffy.
{17928}{17995}Cos I'm not crazy, or cos I don't kill people?
{18003}{18052}Both, actually.
{18063}{18156}I hear you. I can't kill her,|fun as it may sound.
{18183}{18234}I can make her cry uncle, though,|and I mean to.
{18243}{18338}Don't let your feelings about Faith|interfere with your work.
{18363}{18451}Stopping Faith is my work.|Take a beat to love this energy.
{18453}{18546}Faith is a footnote. Our priority|is stopping the Ascension.
{18573}{18623}Easier said than done, Monarchy Boy.
{18633}{18692}If you don't have|something constructive to add...
{18693}{18752}You guys wanna know about the Ascension?
{18768}{18842}Well, meet the only living person|who's ever been to one.
{18858}{18918}About 800 years ago|in the valleys above the Urals,
{18918}{18992}there was a sorcerer there|who achieved Ascension.
{19008}{19072}He became the embodiment|of the demon Lohesh.
{19083}{19152}I was there cursing a shepherd|who'd been unfaithful.
{19158}{19250}- His wife had wished that all his sheep...|- Could we cut back to the chase?
{19278}{19335}Sorry. Lohesh was...
{19398}{19458}It... it decimated the village within hours.
{19473}{19523}Maybe three people got out.
{19533}{19640}I've seen some horrible things. I've been the|cause of most of them, actually, but this...
{19653}{19758}I'm sorry. Lohesh was|a four-winged soul killer. Am I right?
{19773}{19849}I was given to understand|that they're not that fierce.
{19863}{19958}- Of all the demons we've faced...|- You've never seen a demon.
{19968}{20054}Excuse me. Killing them|professionally four years running.
{20073}{20166}All the demons that walk the Earth are|tainted, are human hybrids like vampires.
{20178}{20283}The Ascension means that a human|becomes pure demon. They're different.
{20313}{20343}- Different?|- How?
{20343}{20417}Well, for one thing, they're bigger.
{20435}{20511}The kids are here,|the parents off to the side there.
{20555}{20671}We'll go up, they'll play the processional,|and then you'll give the address.
{20690}{20759}- It all looks wonderful.|- As long as nobody makes any trouble.
{20765}{20819}Stop worrying.|Just make sure the kids show up.
{20825}{20931}Anybody who doesn't feel like coming,|they'll just have to live without a diploma.
{20945}{20996}- They'll be here, sir.|- Call me Richard.
{21035}{21097}You've done a great job here.
{21110}{21201}I know things are, well,|different here in Sunnydale.
{21215}{21306}We've seen all sorts of things. What's|important is that we keep it under control.
{21320}{21390}- And that's what you've done.|- I believe in order.
{21410}{21483}Sunnydale owes you a debt. It will be repaid.
{21530}{21603}Yes, sir. We'll mark that invoice "Paid in full".
{21665}{21728}It doesn't sound like Lohesh.|The rituals are all different.
{21740}{21796}- I wish that was a relief.|- What's goin' on?
{21815}{21865}How come Evil Girl's in the mix?
{21875}{21919}Anya witnessed an Ascension.
{21965}{21990}OK, then.
{21995}{22075}What about the spiders? The Mayor|had a box of spiders that he had to eat.
{22085}{22140}Or the box of... I wanna say "gravlax"?
{22160}{22210}- Gavrok.|- It doesn't ring a bell.
{22220}{22280}Well, there must be something|that would be helpful.
{22280}{22324}So...
{22385}{22429}This is the inner sanctum.
{22490}{22609}Faith tells me this is where you folks like|to hang out, concoct your little schemes.
{22640}{22734}It's just nice to see that some young people|are still interested in reading
{22745}{22796}in this modern era.
{22865}{22929}So, what are kids reading nowadays?
{22970}{23048}"The beast will walk upon the earth,|and darkness will follow."
{23060}{23144}"The several races of man will be|as one in their terror and destruction."
{23165}{23245}That's kinda sweet.|Different races coming together.
{23255}{23347}You never get even a little tired|of hearing yourself speak, do you?
{23390}{23446}That's one spunky little girl you've raised.
{23525}{23582}I'm gonna eat her.
{23720}{23754}Whoa.
{23780}{23848}Well, now, that was a little thoughtless.
{23900}{23973}Violent outbursts like that?|In front of the children?
{23990}{24069}You know, Mr Giles,|they look to you to see how to behave.
{24080}{24124}Get out.
{24185}{24247}I smell fear. That's smart.
{24320}{24407}But some of your deaths will be quick,|if that's worth anything.
{24425}{24487}Well... See you all at graduation.
{24530}{24603}You don't wanna miss|my commencement address.
{24620}{24677}It's gonna be one heck of a speech.
{25001}{25062}Anya, wait. Where are you goin'?
{25076}{25175}Anywhere. If there's a lunar shuttle|going up anytime soon, I'm on it.
{25181}{25236}We need you here. You might be able to help.
{25256}{25301}Or I might be able to live.
{25301}{25397}You can't stop the Ascension, Xander.|You were right the first time.
{25421}{25491}The only thing|any sane person can do now is run.
{25526}{25580}- What's her saga?|- She's freakin'.
{25601}{25687}- About what?|- The Mayor is gonna kill us all.
{25736}{25788}- Are you gonna go to fifth period?|- I might skip it.
{25796}{25838}Yeah. Me, too.
{25916}{25978}Buffy, I'm home. Do you wanna go to a...
{26036}{26090}What are you doing?
{26126}{26179}You're running away again?
{26201}{26281}- And you're taking my clothes.|- Mom, I need you to leave town. Tonight.
{26291}{26365}- Buffy, I'd miss your graduation.|- Yeah, that's sort of the idea.
{26381}{26454}- I wouldn't dream of it.|- Graduation is a pointless ceremony
{26471}{26592}where you sit around till someone hands|you a piece of paper that says you graduated.
{26606}{26676}And maroon does nothing|for my complexion, so don't argue, OK?
{26681}{26764}What, is some terrible demon|going to attack the school?
{26861}{26905}I see.
{26936}{27031}You know, Buffy, looking back|at everything that's happened...
{27056}{27150}- I should have sent you to a different school.|- Just promise me you'll be far away.
{27161}{27243}I am not leaving you to face|an awful monster. If I go, you go with me.
{27251}{27321}- You know that I can't.|- Well, then, I can't either.
{27386}{27456}- I know sometimes you wish I were different.|- Buffy, no.
{27461}{27510}I wished I could be a lot of things for you.
{27521}{27613}A great student,|a star athlete, remotely normal.
{27656}{27708}I'm not.
{27716}{27805}But there is something I do better|than anybody else in the world.
{27806}{27896}I'm gonna fight this thing.|But I can't do it and worry about you.
{27911}{27984}- Buffy, I just can't...|- You stay, you'll get me killed.
{28031}{28082}You have to trust me on this.
{28091}{28131}Can you do that?
{28425}{28474}This is so frustrating.
{28500}{28556}- Nothin' useful?|- No, it's great.
{28575}{28674}If we want to make farms invisible|or communicate with shrimp,
{28695}{28748}I've got the goods right here.
{28770}{28831}Our lives are different than other people's.
{28860}{28943}Who am I kidding? I'm not gonna|find a spell to stop the Ascension.
{28965}{29072}I'm no witch. I can't even|change poor Amy back to a person.
{29160}{29282}But you got the swinging Habitrail goin'.|I think Amy's in a good place emotionally.
{29295}{29357}- Oz.|- What?
{29385}{29468}Could you just pretend to care|about what's happening, please?
{29505}{29585}- You think I don't care?|- I think we could be dead in two days' time,
{29595}{29664}and you're being ironic detachment guy.
{29685}{29757}- Would it help if I panic?|- Yes. It'd be swell.
{29760}{29831}Panic is a thing people can|share in times of crisis,
{29850}{29936}and everything's really scary now,|and I don't know what's gonna happen.
{29955}{30034}And there's things you're supposed|to get to do after high school,
{30045}{30132}and I was looking forward to doing them,|and we're probably just gonna die.
{30150}{30209}And I'd like to feel that maybe you would...
{30345}{30406}- What are you doin'?|- Panicking.
{31216}{31260}Stealthy!
{31291}{31379}Not my best entrance.|I think they were moppin' in the halls.
{31411}{31461}What are you doing here?
{31471}{31542}I checked in with Giles.|He asked me to back you up.
{31561}{31644}- He's afraid I'll run into Faith.|- And you're not?
{31651}{31715}It's gonna happen sooner or later.
{31726}{31770}What's that?
{31786}{31851}A report. Excavation of some old lava bed.
{31861}{31927}The guy was a volcano-ologist or something.
{31951}{32005}Anything that connects him to the Mayor?
{32011}{32080}I looked through it,|but all I understood were the commas.
{32086}{32140}I'll bring it to Giles,|see if he can do better.
{32161}{32207}Let me give you a hand.
{32506}{32559}Thank you, but I can take it from here.
{32566}{32655}- It's all right. I'll walk you there.|- Look, I don't need an escort.
{32671}{32745}I'm a big girl, with superpowers, remember?
{32761}{32806}I don't need you crowding me.
{32806}{32888}- I didn't think I was.|- No, of course you don't.
{32911}{32988}You just show up at the prom|and then you disappear into the ozone.
{33001}{33045}For all I know, you left town.
{33046}{33116}Are you mad at me for being|around too much, or not enough?
{33136}{33185}- Duh! Yes.|- Which?
{33196}{33251}- What?|- I don't get you.
{33256}{33300}No, you don't. Not any more.
{33316}{33396}Are you just making this harder|to make this easier on yourself?
{33406}{33454}Could we stop with the brain-teasers?
{33466}{33567}- I just wish it was over. Done.|- It's not that simple. Once the Mayor...
{33571}{33636}I know. World in peril|and we have to work together.
{33646}{33713}This is my last office romance,|I'll tell you that.
{33736}{33827}- You want me out of your face?|- Isn't it even a little hard for you?
{33841}{33909}How can you ask me that?|Just cos I'm not acting like a brat...
{33916}{33995}- It's nice to know what you think of me.|- What do you expect me to say?
{34006}{34046}I can't do this any more.
{34066}{34144}I can't have you in my life|when I'm trying to move on.
{34261}{34305}Angel.
{34426}{34476}Missed the heart.
{34486}{34527}Meant to.
{34649}{34709}- There.|- OK, ready?
{34709}{34763}- Yeah.|- On three.
{34784}{34855}- One...|- I knew you were gonna do that.
{34859}{34942}- Not too much blood here.|- I heal fast. I should be all right.
{34964}{35043}- I'm just glad Faith's such a suck shot.|- Are we sure it was her?
{35054}{35127}Well, I've narrowed down|my list of one suspect.
{35159}{35210}- Fascinating.|- What?
{35234}{35307}It seems our Mr Worth|headed an expedition in Kauai,
{35309}{35386}digging through old lava beds|near a dormant volcano.
{35399}{35473}- I'm not fascinated yet.|- He found something underneath.
{35489}{35551}A carcass, buried by an eruption.
{35564}{35618}- A carcass?|- A very large one.
{35624}{35735}Mr Worth posits that it might be|some heretofore undiscovered dinosaur.
{35759}{35847}- A demon?|- The Mayor would want to keep that secret.
{35864}{35948}If it's the same kind of demon he's|turning into and it's dead, it means
{35969}{36034}he's only impervious|to harm until the Ascension.
{36044}{36089}In this demon form, he could be killed.
{36089}{36180}Great. So all we need is a million tons|of burning lava. We're saved.
{36194}{36242}Well, it's a start, anyway.
{36254}{36336}OK, you have been a real klutz today.|You need to...
{36359}{36399}Damn.
{36554}{36622}- We'll have to run some tests.|- My shoulder's numb.
{36644}{36735}- You're burning up.|- It's poison. I can feel it.
{36764}{36817}Call the others. Get them here.
{36854}{36931}We need to move him to the safety|of his own bed before the sun comes up.
{36944}{37066}- Will you be able to find out what this is?|- The Council has all known toxins on file.
{37079}{37138}- I'll contact them immediately.|- Thanks.
{37319}{37372}You're gonna be OK.
{38024}{38082}I feel different. You know?
{38099}{38175}I guess that makes sense.|Do you feel different?
{38189}{38244}Oh, no, you've already...
{38249}{38302}Probably no big change for you.
{38339}{38394}It... it was nice.
{38399}{38465}Was it nice? Should this be a quiet moment?
{38504}{38557}I know exactly what you mean.
{38594}{38645}Which part?
{38684}{38737}Everything feels different.
{39074}{39118}Hello?
{39179}{39212}We gotta go.
{39268}{39318}- He's dropped, boss.|- Applause, applause.
{39328}{39452}Right in the back. He pitches over and|Buffy's freakin', looking around all panicked.
{39478}{39531}That should keep her occupied for a spell.
{39538}{39604}- What next?|- The ritual of Gavrok.
{39643}{39712}I have to ingest|several of the inhabitants of this box.
{39718}{39776}- Ingest?|- Eat.
{39838}{39908}- You're wicked gross.|- Well, you don't have to watch.
{39913}{39976}Just go home, take it easy.|It's a big day tomorrow.
{39988}{40080}You gotta give me something to do.|Don't you need anyone dead? Or maimed?
{40093}{40179}- I can settle for maimed.|- You little firecracker.
{40198}{40245}My mom used to call me that.
{40258}{40334}When I was little.|I was always runnin' around...
{40438}{40509}Tomorrow. The Ascension and all that.|Am I gonna get to fight?
{40528}{40583}If everything goes smoothly,|you won't have to.
{40588}{40692}- But how often do things go smoothly?|- So you'll still need me in there.
{40708}{40752}Always.
{40783}{40868}When I was a kid, a couple of miles|outside of Boston there was this quarry.
{40873}{40933}All the kids used to swim there|and jump off the rocks.
{40948}{41018}And there was this one rock, like, 40 feet up.
{41023}{41106}I was the only one that would jump off it.|All the older kids were too scared.
{41128}{41174}Not you, though.
{41188}{41241}No. I could do it easy.
{41308}{41367}Get some rest.
{41443}{41498}Good luck with your spiders there.
{41713}{41760}They should have this at the magic shop.
{41773}{41845}I can run a trace analysis,|see if it's a mystical poison.
{41848}{41919}- I'm a little short on cash.|- Just tell 'em it's for me.
{41938}{41982}Right.
{42148}{42192}Xander?
{42238}{42324}What are you doin' here?|I thought you'd be in Aruba by now.
{42343}{42396}Hey, I'm packed. My car's right outside.
{42403}{42455}I just...
{42463}{42512}I... I had to...
{42538}{42586}What?
{42628}{42685}You could come with me.
{42703}{42766}Come with you? You mean that?
{42793}{42891}Why not? We could just|get in the car and drive and...
{42928}{43013}No one would miss us.|We could take turns driving,
{43033}{43086}keep each other awake.
{43123}{43172}You're going to die if you stay here.
{43228}{43278}I guess I might.
{43288}{43415}When I think that something could happen to|you, it feels bad inside. Like I might vomit.
{43468}{43537}- Welcome to the world of romance.|- It's horrible.
{43543}{43598}No wonder I used to get so much work.
{43603}{43669}Well, I'm sorry I give you barfy feelings.
{43723}{43769}Come with me.
{43828}{43894}- I can't.|- Why not?
{43948}{44012}- I got friends on the line.|- So?
{44068}{44125}That humanity thing's|a work in progress, isn't it?
{44143}{44240}Are you really gonna be that much help to|them? You'll probably just get in the way.
{44248}{44360}- Your stock's plummetin' here, sweetheart.|- Fine. You know what? I hope you die.
{44428}{44478}Aren't we gonna kiss?
{45108}{45158}It'll be OK.
{45198}{45248}You'll be OK.
{45633}{45690}Did you reach the Council?
{45723}{45767}Yes.
{45798}{45842}They...
{45873}{45918}They couldn't help.
{45918}{45962}Couldn't?
{45993}{46069}Wouldn't. It's not Council policy|to cure vampires.
{46083}{46146}- Under special circum...|- Not under any circumstances.
{46158}{46227}- I did try to convince them.|- Try again.
{46278}{46392}They're very firm. We're talking about laws|which have existed longer than civilisation.
{46398}{46451}I'm talking about watching my lover die.
{46518}{46604}I don't have a clue what you're|talking about, and I don't care.
{46608}{46653}Buffy, we'll find a cure.
{46668}{46743}- The Council's orders are to concentrate...|- Orders?
{46863}{46946}I don't think I'm gonna|be taking any more orders.
{46983}{47042}Not from you, not from them.
{47073}{47124}You can't turn your back on the Council.
{47163}{47252}They're in England. I don't think|they can tell which way my back is facing.
{47268}{47321}Giles, talk to her.
{47343}{47402}I have nothing to say right now.
{47448}{47530}Go back to your Council and tell them|until the next slayer comes along,
{47553}{47594}they can close up shop.
{47598}{47643}I'm not working for them any more.
{47658}{47706}Don't you see what's happening?
{47718}{47813}Faith poisoned Angel to distract you,|to keep you out of the Mayor's way.
{47823}{47878}And it's working. We need a strategy,
{47898}{47966}I have a strategy. You're not in it.
{48018}{48063}This is mutiny.
{48183}{48239}I like to think of it as graduation.
{48408}{48468}I can't stay here.|I'll go see if I can help the others.
{48483}{48535}- Of course.|- You'll watch him?
{48543}{48596}I'll call if there's any change.
{48648}{48691}Buffy...
{48693}{48743}You don't know what you're doing.
{48798}{48846}Get a job.
{49128}{49207}Finding the poison wasn't that hard.|It's a mystical compound.
{49218}{49323}The Latin name translates roughly to|"Killer of the Dead". Used on vampires.
{49338}{49373}And the cure?
{49383}{49450}There aren't a lot of instances|of it being cured.
{49473}{49528}- But there are some.|- One or two.
{49533}{49592}Pretty vague accounts.
{49608}{49654}How is he?
{49683}{49728}- Hold it.|- You got somethin'?
{49728}{49777}- I'm not sure.|- Be sure.
{49788}{49889}OK. "Killer of the Dead". That's our boy,|and here's a vamp that walked away from it.
{49908}{49961}Does it talk about the cure?
{49968}{50014}Damn.
{50028}{50082}- Nothing?|- No, it's in here, but...
{50118}{50186}Wait. "Completely reversed the effects."
{50223}{50238}What?
{50238}{50305}Come on, guys.|The suspense is killing Angel.
{50343}{50436}The only way to cure this thing|is to drain the blood of a slayer.
{50673}{50734}- Good.|- Good? What did I miss?
{50793}{50892}No, it's perfect. Angel needs to|drain a slayer, then I'll bring him one.
{50898}{50981}Buffy, if Angel drains Faith's blood,|it'll kill her.
{51003}{51056}Not if she's already dead.
{51202}{51301}A leasing agreement, not in her name. If the|Mayor's putting her up, it might be in his.
{51322}{51437}- Maybe he's charging it to the city.|- Cross-reference realty with municipal funds.
{51457}{51523}- You wanna drive?|- Sorry.
{51607}{51679}Someone should take over|for Giles after a while, watch Angel.
{51697}{51764}I don't mean to play devil's advocate,|but are you up to this?
{51772}{51816}It's time.
{51817}{51861}We're talking to the death.
{51877}{51960}I can't play kid games any more.|This is how she wants it.
{52012}{52071}- I just don't wanna lose you.|- I won't get hurt.
{52087}{52137}That's not what I mean.
{52162}{52210}Just get me an address.
{53122}{53172}I got it.
{53767}{53817}Thought I'd stop by.
{53872}{53950}- Is he dead yet?|- He's not gonna die.
{53977}{54042}It was a good try, though. Your plan?
{54067}{54144}The Mayor got me the poison.|He said it was wicked painful.
{54187}{54251}- There's a cure.|- Damn. What is it?
{54262}{54317}Your blood.
{54382}{54460}As justice goes,|it's not unpoetic, don't you think?
{54472}{54533}Come to get me?|You're gonna feed me to Angel?
{54592}{54689}- You know you're not gonna take me alive.|- Not a problem.
{54697}{54777}Well, look at you.|All dressed up in big sister's clothes.
{54847}{54905}You told me I was just like you.
{54982}{55029}That I was holding it in.
{55042}{55084}Ready to cut loose?
{55117}{55181}- Try me.|- OK, then.
{55252}{55313}Give us a kiss.
{56632}{56729}You're not getting tired, are you?|I'm just starting to feel it.
{57292}{57338}Stick around.
{57396}{57440}Buffy...
{57621}{57665}Right. Right.
{57756}{57825}- Something about the demon?|- Villagers near the volcano
{57831}{57898}make reference to the legend of Olukai.
{57906}{57965}It might be a bastardisation of "Olvikan".
{57981}{58086}- Who's Olvikan?|- I know it's a demon. I might have a picture.
{58116}{58191}It's a good thing no one ever wanted|to check these books out, huh?
{58191}{58257}- Yes, it's very convenient.|- Come on, Olvikan.
{58551}{58603}We're gonna need a bigger boat.
{58986}{59039}My God, what a feeling.
{59061}{59121}The power of these creatures.
{59136}{59189}It suffuses my being.
{59286}{59340}I can feel the changes begin.
{59376}{59473}My organs are shifting, merging,|making ready for the Ascension.
{59511}{59600}Plus these babies are high in fibre. And|why become a demon if you're not regular?
{59616}{59675}Am I right?
{59676}{59726}We don't knock during dark rituals?
{59736}{59803}Sir, there may be trouble. At Faith's.
{60405}{60495}What's the matter? All that killing|and you're afraid to die?
{60810}{60877}- That's mine.|- Well, you're about to get it back.
{61185}{61232}Man, I'm gonna miss this.
{61530}{61565}You did it.
{61845}{61898}You killed me.
{62175}{62222}Still won't help your boy, though.
{62295}{62348}You shoulda been there, B.
{62430}{62489}Quite a ride.