{1}{1}25.000
{350}{500}Subtitles made by |senor_datel@post.sk
{534}{559}Okay, children, let's take our seats.
{570}{596}Did you take attendance, Mr. Slave?
{737}{604}All donesy wunsy.
{618}{630}Okay, let's all take out
{631}{661}our math homework and go |over the problems.
{662}{706}Mmmath homework, Mmmath homework.
{707}{729}Where did I file that?
{730}{760}Oh, and by the way, children,
{761}{775}there's a walkout scheduled
{776}{800}today to protest the war in Iraq.
{801}{821}So, uh, if you're against
{822}{837}the war, run along outside,
{838}{858}and if you're for the war, uh,
{859}{886}stay here and we'll do math problems.
{919}{967}We got out of schoo-l!
{968}{1005}No more school toda-ay!
{1006}{1025}What should we do?
{1026}{1039}Let's go see a movie!
{1040}{1053}No war! No war!
{1054}{1065}No war! No war!
{1066}{1078}No war! No war!
{1079}{1096}No war! No war!
{1097}{1122}No war!
{1123}{1213}No war, m'kay?!
{1214}{1236}No war, m'kay?!
{1247}{1274}Oh uh, here you go,boys.
{1275}{1293}These will help you protest.
{1294}{1318}It's good to see that you care
{1319}{1343}about peace, boys, m'kay?
{1344}{1361}No war, m'kay?!
{1362}{1393}Excuse me, boys.
{1394}{1414}Tom Stansel, HBC news.
{1415}{1425}Can you kids tell me
{1426}{1456}why you marched out of school today?
{1475}{1511}Uh... war?
{1512}{1544}Right. What about the war?
{1545}{1577}Ih ih ih-t's g-gay?
{1601}{1611}Uh huh, and what aspect of it
{1612}{1635}do you think is most gay?
{1636}{1671}Uuuh, n-no blood for oil.
{1672}{1685}Yeah.
{1686}{1709}War is not my voice.
{1710}{1738}Bush is a Naizi
{1748}{1778}Hey all you unAmerican bastards!
{1779}{1798}If you don't like America,
{1799}{1822}why don't you git out?!
{1823}{1869}Don't you call us unAmerican!
{1870}{1888}This country was
{1889}{1910}founded on the right to protest!
{1911}{1929}M'kay?
{1930}{1949}Yeah! Right!
{1950}{1983}If the Founding Fathers saw you |burning your flag
{1984}{2007}an' callin' the President a Nazi,
{2008}{2031}they'd roll over in their grave!
{2032}{2058}Yeah! Right!
{2059}{2104}The Founding Fathers would agree |with our right to protest!
{2105}{2146}Foundin' Fathers would kick all your asses!
{2147}{2188}Boys, what do you think the |Founding Fathers would say?
{2207}{2235}...Eh the... Founding who?
{2236}{2346}Well, I hope you little Commies |are pretty pleased with yourselves!
{2347}{2379}Going out there and protesting America,
{2380}{2410}and then saying on national television
{2411}{2442}that you don't even know who |the Founding Fathers are!
{2443}{2480}You kids don't know squat |about America, do you?!
{2511}{2538}Mmuh well, not really, no.
{2539}{2563}Well that's just jingles!
{2564}{2595}Because I'm assigning all you |little flag-burners
{2596}{2626}a full report on seventeen seventy-siyix,
{2627}{2654}and the Founding Fathers!
{2655}{2671}Awwwwww!
{2672}{2685}SHUT UP!
{2686}{2709}I want you all in your study groups of four,
{2710}{2729}and if you can't give an outstanding report
{2730}{2754}on what the Founding Fathers |would have to say
{2755}{2773}about all this protesting,
{2774}{2796}then it's Fs for you!
{2886}{2952}Ugh. UGHuh.
{2976}{2989}I can't do it!
{2990}{3014}This is waaay too much material |for a nine-year-old!
{3024}{3074}Oh no you don't, Cartman!
{3075}{3097}Every time we get put in a study group,
{3098}{3122}you sit on your ass while |the rest of us do all the work!
{3123}{3151}But you guys are such better |studiers than me.
{3152}{3171}I know you can pull it off.
{3172}{3198}You're gonna read this stuff |and study like the rest of us!
{3209}{3254}Maaaa. M-maaaa.
{3255}{3274}Shut up and study!
{3275}{3364}Maaaa. Mah mah mh.
{3524}{3583}Hmmm, 1776.
{3584}{3602}When our Founding Fathers created America.
{3603}{3639}I wonder what  it used to be |like in those days?
{3640}{3687}In those days? In those days? |In those days?
{3688}{3715}What are you doing?
{3716}{3739}I'm trying to have a flashback.
{3740}{3753}(A what?)
{3754}{3777}You know. If I have a flashback,
{3778}{3805}then I can see what 1776 was |like first-hand!
{3806}{3828}No, you just have to study.
{3829}{3847}Nonono. I've seen this work before.
{3848}{3864}Just give me a second.
{3865}{3882}Oh okay, okay.
{3883}{3929}How about this: Say guys, |1776 was so long ago.
{3930}{3959}I wonder what life would |have been like back  then?
{3960}{4009}Back then? Back then? Back then?
{4098}{4120}Um... Oh waitwait, I know,  I know!
{4121}{4146}Heheh, you know guys,
{4147}{4176}I don't even care about 1776.
{4177}{4219}It was so long ago, that |I don't think it has anything to do with me.
{4220}{4294}With me.  With... anything |to do with me. With me.
{4295}{4316}That isn't gonna work, dumbass!
{4317}{4351}Kids, let's keep it down for study group,
{4352}{4391}or else  Mr. Garrison is |going to punish me.
{4392}{4414}Just face it, Cartman.
{4415}{4430}You're  gonna have to study!
{4431}{4475}Maaaaa. Meh mameh, Maaaaa!
{4520}{4542}There! All finished.
{4543}{4584}From now on, this is |the pro-war side of town,
{4585}{4625}and that's the unpatriotic side.
{4626}{4687}How about we call this |the rational side of town,
{4688}{4713}and that the redneck side?!
{4714}{4739}Hahahaha, yeah.
{4740}{4778}You just keep all your flag burnin'
{4779}{4809}and your hippie-rock protest |songs on YOUR side o' the town!
{4824}{4837}Hey wait a minute,
{4838}{4869}your side of town has the post office.
{4870}{4897}Well your side has the grocery store.
{4898}{4932}Well you can come to our side |of town to use the post office
{4933}{4966}and we can go to your side |to use the grocery store.
{4967}{5004}Aaah, can we cross the line |to take our kids to school?
{5005}{5037}W-hell, naturally you could |cross the line for that.
{5038}{5063}Just like ...we could cross |the line for hardware,
{5064}{5087}supplies, gas, and pharmaceutical needs.
{5088}{5126}Yup, yes sir, yeah, right, uh huh.
{5127}{5168}Hey everybody, this is |never going to work.
{5169}{5184}Don't you  see?
{5185}{5210}All this dividin' up the town,
{5211}{5235}it's just ridiculous.
{5236}{5260}What  we really should be doing,
{5261}{5282}is just beatin' the hell out of
{5283}{5302}each other like we were.
{5314}{5332}He's right.
{5333}{5382}Boy, do I feel like a fool.
{5416}{5437}Cartman, what the hell are you doing?!
{5438}{5453}You're suppsoed  to be studying!
{5454}{5471}That's what I'm doing.
{5472}{5485}I'm about to find out all
{5486}{5502}about what happened back in 1776.
{5503}{5522}How?!
{5523}{5552}All I have to do is be thinking |about American history
{5553}{5575}when I walk through this doorway.
{5576}{5601}I'll trip the rope, causing |the rock to fall on my head.
{5602}{5637}And then I will have a flashback |to the times of our Founding Fathers!
{5638}{5678}Cartman, you are hereby declared |a full-fledged retard!
{5679}{5708}Haha, make fun of me all you want, Kyle!
{5709}{5733}But I will  have the last laugh.
{5734}{5781}Gentlemen, if you will clear |the doorway, please?
{5896}{6033}Cartman? Cartman??
{6073}{6069}Benjamin Franklin?
{6070}{6094}No, turdpants, it's Kyle!
{6095}{6173}Kyle! Get out of my flashback |you goddamn Jew
{6208}{6220}Rabble! Rabble! Rabble!
{6221}{6239}Rabble! Rabble! Rabble!
{6240}{6251}Rabble! Rabble! Rabble!
{6252}{6288}Okay, people. What are we |rabbling about now?
{6289}{6317}Mayor, our peace rally has always been
{6318}{6342}set for this Saturday!
{6343}{6363}Now, these pro-war bastards are
{6364}{6400}suddenly trying to say |they get the town square.
{6401}{6423}That's bullcrap, Mayor!
{6424}{6460}Our rally to support the war |was set up months ago!
{6461}{6495}There was no war months ago!
{6496}{6538}Hey, if you don't like America, |then you can git out!
{6539}{6556}Look, nobody wants to hear
{6557}{6602}a bunch of twangy country music |prowar proopaganda!
{6603}{6644}Well nobody wants to hear |a bunch o' rock protest songs!
{6645}{6689}Well up yours, rednecks!
{6690}{6700}Rabble! Rabble! Rabble!
{6701}{6717}Rabble! Rabble! Rabble!
{6718}{6727}Rabble! Rabble! Rabble!
{6728}{6736}Quiet people!
{6737}{6767}The town square is public space.
{6768}{6789}That means if neither group |will nicely and maturely
{6790}{6811}move the day of its rally,
{6812}{6849}I'll just have have to give |the town square to both groups.
{6850}{6875}All right, that's fine!
{6876}{6917}Because our war support songs |will be a thousand times better!
{6918}{6936}Oh, you think so?
{6937}{6959}Bring the shizzle!
{6960}{6981}We'll trizzle the shizzle |all over the hizzle!
{6982}{7015}Yeah?! See you Saturday,
{7016}{7051}makizzer shanna sharilla shaz iuznatch gazizzah!
{7052}{7084}Cartman?
{7085}{7115}Cartman? You'd better be |studying, God-damnit!
{7134}{7163}Ah, Stan, Kyle, Kenny, |you're just in time.
{7164}{7176}Oh no...
{7177}{7186}Oh yes!
{7187}{7219}I am just about to flash |back to the days of our Foundig Fathers!
{7220}{7247}Cartman, you're supposed |to be studying!
{7248}{7269}What the hell  is all this?!
{7270}{7288}I have programmed TiVo to record
{7289}{7308}over fifty hours of the |History channel.
{7309}{7321}When TiVo is full,
{7322}{7343}both TiVo and I will be |dropped into the water,
{7344}{7362}combining our |electrowhatever fields
{7363}{7381}and sending me into |a flashback of history!
{7382}{7415}Uh Cartman, I think that's |a really bad idea.
{7416}{7445}Or a really sweet one.
{7446}{7462}Your TiVo is full.
{7463}{7488}Whoa, here it goes!
{7625}{7641}Cartman?
{7642}{7667}Cartman??
{7668}{7690}Aww crap.
{7786}{7806}Ohhh awesome!!!
{7833}{7857}Worthy young lad, are you all right?
{7858}{7871}Yeah yeah.
{7872}{7884}Can you tell me what year it is?
{7885}{7899}This year?
{7900}{7924}Why it's 1776, it is.
{7925}{7940}Oho yes!
{7941}{7963}I did it I did it!
{7964}{7986}Would you like a ride into town?
{7987}{8003}I'm on my way to Master |Thomas Jefferson's hosue
{8004}{8029}to get a very important document, I am.
{8030}{8060}Oho kick fucking ass, dude!
{8091}{8110}Never seen you around here, friend.
{8111}{8130}Might you be from  up North?
{8131}{8150}No, I'm not from here at all.
{8151}{8164}I'm having a flashback.
{8165}{8182}A flashback?
{8183}{8196}Why, what is that?
{8197}{8217}Well you know, it's a...
{8218}{8241}H-ho,awesome!
{8242}{8290}Look at me, I'm back in time, in 1776.
{8291}{8308}With gaslight corners,
{8309}{8325}cobblestone streets,
{8326}{8352}and humble houses made of bricks.
{8353}{8381}What a special magic time,
{8382}{8415}and it's all alive for me
{8416}{8442}I'm so glad Stan and Kyle aren't here.
{8443}{8497}I hate those guys, seriously.
{8498}{8536}Seriuosly hate those guys.
{8537}{8588}Hate Stan and Kyle.
{8642}{8665}Is he going to be all right, doctor??
{8666}{8688}Your son tried to kill himself
{8689}{8719}in a ritualistic  fashion |I've never seen before.
{8720}{8751}His chances of surviving are very slim.
{8752}{8785}I'm so sorry.
{8786}{8813}Oh baby baby, you can't die.
{8814}{8824}Yeah.
{8825}{8844}We have a report to do, asshole!
{8845}{8867}Get up! Get up!!
{8868}{8882}Whoa. Easy, Kyle.
{8883}{8901}But it's not fair!
{8902}{8925}We have to do a full report |on the  Founding Fathers,
{8926}{8955}and Cartman got out of helping us again!
{8956}{8983}I gues we're just gonna have |to do it with the three of us!
{8984}{9000}Come on, guys!
{9001}{9046}I know you're in a very dark |place now, sweetie.
{9047}{9071}But  you must come toward the light!
{9072}{9104}Come toward the light!
{9119}{9133}Here we are, then.
{9134}{9162}The current residence of |Master Thomas Jefferson.
{9163}{9183}Super neato!
{9184}{9227}I'm afraid you'll have to wait here.
{9228}{9262}But, I need to talk to the |Founding Fathers to do my report.
{9263}{9281}Sorry.
{9282}{9301}Only the official messenger boy
{9302}{9324}is allowed to talk to Mister Jefferson
{9325}{9342}Oh, okay.
{9343}{9369}I guess I understand.
{9379}{9429}I don't wanna wait for our life to be over...
{9430}{9544}I don't wanna wait for our life to be over...
{9577}{9618}Hello. I am Thomas Jefferson.
{9619}{9656}And I am the official messenger boy, I am.
{9657}{9674}Very well.
{9675}{9710}Take this document  |to the Continental Congress.
{9711}{9754}Wow, the Declaration |of Independence Day.
{9755}{9782}Some favir going to war with England
{9783}{9813}and others want to avoid war at all cost.
{9814}{9835}It's a bitch, ain't it?
{9836}{9882}Perhaps this document will |make the reasons for war obvious to all.
{9883}{9916}Good luck, young messenger!
{9917}{9939}Now make haste!
{9962}{10003}Okay, so Thomas Jefferson wrote |the Declaration of Independence,
{10004}{10023}then the Continental Congress-
{10024}{10065}No war! No war! No war!
{10066}{10073}Oh, Jesus...
{10074}{10110}Uh, boys, would you mind clearing |the living room.
{10111}{10144}We have to practice our |big war protest song.
{10145}{10161}Dad, we have to study.
{10162}{10183}Mr. Garrison is making |us do a presentation
{10184}{10210}on what the Founding Fathers |would say about the war.
{10211}{10252}Hey... That's a terrific idea!
{10253}{10286}Yeah! We could have the boys |do their presentation
{10287}{10318}as part of our peace rally on Saturday!
{10319}{10340}Oh, no, nononono.
{10341}{10358}Support our troops!
{10359}{10378}Support our troops!
{10379}{10401}Support our troops!
{10402}{10423}See? I told you they had your son.
{10424}{10437}Kenny.
{10438}{10471}What are you doing over |here with all these unAmerican traitors?!
{10472}{10485}(I'm doing my homework.)
{10486}{10521}The boys are going to give |a presentation at our rally
{10522}{10551}about how the Founding Fathers would agree
{10552}{10581}with our right to protest!
{10582}{10624}Actually, we hadn't really |come to a decision-
{10625}{10664}Look! My son is a patriot |and LOVES his country!
{10665}{10685}Come on, Kenny!
{10686}{10698}(But Dad, I-)
{10699}{10714}NOW!
{10715}{10722}Yeah!
{10723}{10734}Support our troops!
{10735}{10745}Support our troops!
{10746}{10756}Support our troops!
{10757}{10762}Support our troops!
{10763}{10777}Kenny, no- ohhh!
{10778}{10783}Awww.
{10784}{10817}Awww, now we lost two |in our study group!
{10818}{10827}God damnit!
{10828}{10859}Can you believe those |hick sons of bitches?
{10860}{10889}Manipulating those kids |to be on their side.
{10890}{10919}Disgraceful! Stan and Kyle,
{10920}{10944}it's up to you to show |all those war-mongerers
{10945}{10969}that the Founding Fathers |agree with us!
{10970}{11000}Yeah, that's right!
{11001}{11013}Come on, guys!
{1014}{1023}Get back to work!
{11024}{11038}Do you think kids in every town
{11039}{11064}have to deal with this crap?
{11134}{11169}Enter, young messenger.
{11254}{11303}I am John Hancock, |President of the Congress.
{11304}{11319}Wow.
{11320}{11338}Mr. John Adams?
{11339}{11354}Aye.
{11355}{11382}Will you do the honors of reading
{11383}{11404}the document to Congress, please?
{11440}{11463}WHEN in the Course of human Events,
{11464}{11499}it becomes necessary for one People to-
{11510}{11540}-we mutually pledge |to each other our Lives,
{11541}{11571}our Fortunes, and our sacred Honor.
{11572}{11654}P.S. - Every Thursday |should be Free Ice Cream Day.
{11706}{11716}Excuse me,
{11717}{11752}but does this Declaration actually suggest
{11753}{11782}that we should go to go war with England?
{11783}{11812}We have no choice, Mr. Dickinson.
{11813}{11877}All right everyone,
{11878}{11930}thank you all for comin' |out to protest the war, m'kay?
{11931}{11974}Don't kid yourselves.
{11975}{12020}These people have come |out to support our troops, right?!
{12048}{12077}And now, Randy Marsh is gonna sing
{12078}{12115}a protest song he wrote about the war.
{12116}{12143}Oh no you don't!
{12144}{12171}We're doing our pro-war song first!
{12172}{12190}Yeah!
{12191}{12209}The last thing these people want
{12210}{12238}is a bleedin'-heart rock protest song!
{12239}{12266}People, I told you,
{12267}{12285}you have to share the stage.
{12300}{12341}Nobody wants to here another |pro-war country song!
{12342}{12374}Well excuse me if...
{12375}{12426}I'm a little bit country.
{12427}{12476}Well I'm a little bit rock-n-roll!
{12477}{12519}I'm a little for supportin' our troops.
{12520}{12579}And I'm a little for bringin' them home.
{12580}{12613}I believe freedom isn't free.
{12614}{12642}No, but war shouldn't be our goal.
{12643}{12685}We must defend our country.
{12686}{12724}If it means war, then we say NO!
{12725}{12751}Yeehaw!
{12761}{12829}Did you forget them towers in New York?
{12830}{12886}Did you forget how it made you feel
{12887}{12929}To see them towers come down?
{12930}{12959}Were you like me?
{12960}{13007}Did you think it weren't real?
{13008}{13032}I like to rock,
{13033}{13097}but I don't wanna rock Iraq!
{13098}{13135}The only kind of rockin' America
{13136}{13194}should do is the kind that |we can all dance to, yeah!
{13195}{13281}We got GPS, ICBMs, and good |old-fashioned lead.
{13282}{13325}We're gonna show Saddam |what America means;
{13326}{13369}that son of a bitch will be dead.
{13370}{13419}Why are we fightin' this war?
{13420}{13462}There's a man in the office |we didn't vote for.
{13463}{13496}They didn't give me a choice.
{13497}{13534}War is not my voice!
{13535}{13557}Yeaaaaahhhh!
{13558}{13640}We must go to war!
{13641}{13662}But what about the violence?!
{13663}{13679}The lives lost?!
{13680}{13698}If  we found a country,
{13699}{13732}it should be founded on |peace and diplomacy.
{13733}{13767}England will only understand one thing:
{13768}{13785}Force.
{13786}{13816}I must state again for the record that
{13817}{13829}South Carolina, North Carolina,
{13830}{13852}Pennsylvania, Maryland,
{13853}{13884}and  Georgia are against war!
{13885}{13911}Yeah, because you don't |care about the fate
{13912}{13937}of the Colonies like we do!
{13938}{13964}You're all unpatriotic!
{13965}{13985}And if you don't like the Colonies,
{13986}{14013}then you can git out!
{14014}{14037}Don't you call us unpatriotic!
{14038}{14059}We're protesting  this war
{14060}{14079}because we care so deeply
{14080}{14101}for the fate of our Colonies!
{14102}{14121}You are all unpatriotic
{14122}{14139}for leading the Colonies into a war
{14140}{14158}that half of them don't want!
{14159}{14206}Whoa, how very very relevant.
{14252}{14292}Tom, I'm standing in the town square
{14293}{14311}where the war rally has been going on
{14312}{14340}for an incredible eighty-seven hours.
{14341}{14368}The crowd still appears to be split
{14369}{14390}right down the middle
{14391}{14409}- half of them support country music,
{14410}{14428}and the other half rock-n-roll.
{14429}{14448}Let's listen in.
{14449}{14469}And now we'd like to bring out
{14470}{14496}a couple of very  special |South Park students
{14497}{14516}who did a report
{14517}{14533}on what the Founding Fathers
{14534}{14564}would have to say about the war.
{14598}{14641}Booooo!!
{14642}{14653}For you people
{14654}{14676}who still think war is the  answer,
{14677}{14707}perhaps you can listen to the voices ...
{14708}{14753}of the  children.
{14808}{14831}Uh, we didn't do it.
{14832}{14854}What?
{14855}{14881}We didn't do our homework.
{14882}{14895}Boys!
{14896}{14919}You were supposed to come out here
{14920}{14947}and tell everyone |about the Founding Fathers!
{14948}{14974}Well, first we lost one study partner
{14975}{14993}when Cartman put himself in the hospital,
{14994}{15008}and then they took Kenny away,
{15009}{15030}and  then Kyle forgot to set his clock
{15031}{15042}ahead for Dalight Saving,
{15043}{15066}so we couldn't find anything |in the history books
{15067}{15082}about Iraq and  then-
{15083}{15099}That's because the Founding Fathers
{15100}{15124}would have  supported the war!
{15125}{15152}The Founding Fathers would |have protested like us!
{15153}{15178}Support!
{15179}{15195}Protest!
{15196}{15213}Country!
{15214}{15236}Rock-n-roll!
{15401}{15406}Rabble Rabble Rabble
{15407}{15414}Rabble Rabble Rabble
{15415}{15424}Rabble Rabble Rabble
{15425}{15434}Rabble Rabble Rabble!
{15435}{15488}We cannot found a country based on war!
{15489}{15528}We cannot found a country |that is afraid to fight!
{15529}{15542}Rabble!
{15543}{15559}Rabble Rabble Rabble
{15560}{15569}Rabble Rabble Rabble
{15570}{15580}Rabble!
{15600}{15621}Oh my, it's Benjamin Franklin.
{15622}{15629}It's Benjamin Franklin.
{15630}{15650}It's Benjamin Franklin.
{15651}{15677}Oh, it's Benjamin Franklin.
{15678}{15687}It's Benjamin Franklin.
{15688}{15699}It's Benjamin Franklin.
{15700}{15738}Mr. Franklin,
{15739}{15755}where do you stand on the war issue?
{15756}{15819}I believe that if we are to |form a new country,
{15820}{15864}we cannot be a country |that appears war-hungry
{15865}{15893}and violent to the rest of the world.
{15894}{15940}However, we also cannot be a country
{15941}{15968}that appears weak and unwilling to fight
{15969}{15993}to the rest of the world.
{15994}{16039}So, what if we form a country
{16040}{16078}that appears to want both?
{16091}{16138}Yes. Yes of course.
{16139}{16164}We go to war,
{16165}{16204}and protest going to war |at the same time.
{16205}{16227}Right.
{16228}{16245}If the people of our new country
{16246}{16268}are allowed  to do whatever they wish,
{16269}{16286}then some will support the war
{16287}{16313}and some will protest it.
{16314}{16343}And that means that as a nation,
{16344}{16374}we could go to war with |whomever we wished,
{16375}{16398}but at the same time,
{16399}{16419}act like we didn't want to.
{16420}{16458}If we allow the people to protest
{16459}{16484}what the government does,
{16485}{16513}then the country |will be forever blameless.
{16514}{16557}It's like having your cake,
{16558}{16588}and eating it, too.
{16589}{16606}Think of it:
{16607}{16639}an entire nation founded |on saying one thing
{16640}{16661}and doing another.
{16662}{16689}And we will call that country
{16690}{16726}the United States of America.
{16727}{16778}Wow, I get it now!
{16779}{16801}I get it!
{16802}{16824}Whoa, here it goes.
{16825}{16846}I wish I could go back to my time.
{16847}{16873}To my time, to, to my time.
{16874}{16920}Wow!
{17120}{17139}Everyone, stop!
{17140}{17158}Please!
{17176}{17193}The-the child!
{17194}{17219}The child, from the hospital.
{17220}{17240}If you all don't mind,
{17241}{17265}I would like to do my report now.
{17266}{17302}I know what the founding |fathers would say.
{17303}{17327}He does?
{17328}{17338}He does?
{17339}{17360}learned somethin' today.
{17361}{17397}This country was founded
{17398}{17414}by some of the smartest |thinkers the world has ever seen.
{17415}{17434}And they knew one thing:
{17435}{17458}that a truely great country
{17459}{17483}can go to  war, and at the same time,
{17484}{17503}act like it doesn't want to.
{17513}{17532}You people who are for the war,
{17533}{17553}you need the protesters.
{17554}{17570}Because they make the country look
{17571}{17598}like it's made of sane, |caring individuals.
{17599}{17620}And you people who are anti-war,
{17621}{17643}you need these flag-wavers,
{17644}{17665}because, if our whole |country was made up
{17666}{17687}of nothing but soft pussy protesters,
{17688}{17717}we'd get taken down in a second.
{17718}{17740}That's why the founding fathers decided
{17741}{17760}we should have both.
{17761}{17801}It's called "having your |cake and eating it too."
{17802}{17827}He's right.
{17828}{17852}The strength of this |country is the ability
{17853}{17881}to do one thing and say another.
{17882}{17900}Yeah, but...
{17901}{17926}if it weren't for |all you guys protesting,
{17927}{17946}why everyone around the world
{17947}{17970}would hate the American people
{17971}{17999}instead of just the President.
{18000}{18029}And if it weren't for you |people flexing your arms,
{18030}{18056}America could easily get |taken over by terrorists or
{18057}{18085}... or China.
{18086}{18116}I guess we... owe you an apology.
{18117}{18147}Eh-ah, I guess we owe you one.
{18148}{18194}Awww.
{18241}{18253}Cartman?
{18254}{18275}Cartman saved the day?
{18276}{18289}Can't be
{18290}{18314}The Founding Fathers |want you all to know
{18315}{18334}that we can disagree all we want,
{18335}{18366}as long as we agree |that America kicks ass.
{18367}{18417}Hey I'm a little bit country
{18418}{18462}And I'm a little bit rock-n-roll-eh
{18463}{18501}I'll be the muscle of America
{18502}{18540}And me, I'll be the caring soul.
{18554}{18584}When you put us together
{18585}{18612}you get a nation with one goal
{18613}{18649}To thrive and prosper,
{18650}{18680}with a little country and rock and roll.
{18692}{18709}Come on up here, everybody!
{18710}{18782}We're a little bit country,
{18783}{18816}and we're a little bit rock-n-roll
{18817}{18850}We can be a nation that believe in war,
{18851}{18893}And still tells the world that we don't.
{18894}{18926}Let the flag for hyprocisy
{18927}{18953}fly high from every pole
{18954}{18992}We're a little bit country,
{18993}{19024}and we're a little bit rock-n-roll
{19038}{19060}Well, goodnight everybody.
{19061}{19077}It sure has been great
{19078}{19100}bringing you a hundred episodes.
{19101}{19122}We want to thank our guests,
{19123}{19156}the pro-war people.
{19157}{19196}And the anti-war people.
{19197}{19217}What the hell are they doing now?
{19218}{19239}Ah I don't  know.
{19240}{19259}For the war, against,
{19260}{19280}the war, WHO CARES??
{19281}{19332}One hundred episodes!
{19364}{19383}I hate this town.
{19384}{19412}Ah I really really do.
