{5}{33}Previously...
{34}{71}I love you
{71}{97}Oh my god
{100}{241}Here lies the warrior of the people|Let her cross over
{242}{303}I think I was in heaven
{304}{400}I was torn out of there ... by my friends
{401}{435}They can never know
{436}{483}We can't ignore|this kind of behavior
{484}{538}Something needs to be done|before it spins out of control
{539}{598}I'm glad you're here to take care of it
{599}{628}We're getting married
{629}{658}Congratulations
{659}{718}Willow, you are using too much magic
{719}{778}Can we not do this now?
{779}{838}Just ... forget it ever happened
{839}{885}Forget
{929}{1046}Buffy the Vampire Slayer
{1068}{1173}Season 6 Episode 7
{1185}{1349}Transcribed by Joan the English Chick|Psyche Site - http://www. psyche.kn-bremen.de
{1350}{1515}Subtitle - RafPek|SlayerFans - http://www.slayerfans.lava.pl
{1621}{1734}Once More With Feeling
{3944}{4014}Every single night, the same arrangement
{4015}{4095}I go out and fight the fight
{4096}{4173}Still I always feel this strange estrangement
{4174}{4261}Nothing here is real, nothing here is right
{4262}{4324}I've been making shows of trading blows
{4325}{4397}Just hoping no one knows
{4398}{4495}That I've been going through the motions
{4496}{4575}Walking through the part
{4576}{4720}Nothing seems to penetrate my heart
{4737}{4817}I was always brave, and kind of righteous
{4818}{4893}Now I find I'm wavering
{4894}{4974}Crawl out of your grave,|You'll find this fight just
{4975}{5011}Doesn't mean a thing
{5012}{5103}She ain't got that swing
{5104}{5153}Thanks for noticing
{5154}{5226}She does pretty well with fiends from hell
{5227}{5292}But lately we can tell
{5293}{5334}That she's just going through the motions
{5335}{5405}Going through the motions
{5406}{5477}Faking it somehow
{5478}{5634}She's not even half the girl she... owww
{5637}{5714}Will I stay this way forever?
{5715}{5783}Sleepwalk through my life's endeavor?
{5784}{5843}How can I repay...
{5844}{5873}Whatever
{5874}{5993}I don't want to beeeeee...
{5994}{6081}Going through the motions
{6082}{6154}Losing all my drive
{6155}{6230}I can't even see
{6231}{6313}If this is really me
{6314}{6425}And I just want to be...
{6426}{6614}Aliiiiiive
{6863}{6919}Good morning, Buffy!
{6920}{6982}Hey, did Dawn get off to school all right?
{6983}{7102}What? Oh, yeah. I think so
{7103}{7192}Respect the cruller. And tame the donut!
{7193}{7252}That's still funny, sweetie
{7253}{7339}So, no research?
{7340}{7462}Nothing going on? Monsters or whatnot?
{7463}{7547}Good! Good
{7548}{7671}So, did anybody...
{7672}{7761}Last night, you know, did anybody ...
{7762}{7860}... burst into song?
{7882}{7941}Merciful Zeus!
{7942}{7981}We thought it was just us!
{7982}{8039}- Well, I sang but|I had my guitar at the hotel...|- It was bizarre
{8040}{8087}We were talking and then it was like...
{8088}{8121}Like you were in a musical!
{8122}{8181}That would explain the huge backing orchestra
{8182}{8271}I couldn't see and the synchronized|dancing from the room service chaps
{8272}{8322}And we were arguing|and then everything rhymed
{8323}{8361}and there were harmonies and the dance with coconuts|There was an entire verse about the cous-cous
{8362}{8416}It was very disturbing
{8417}{8480}What did you sing about?
{8481}{8600}I don't remember.|But it seemed perfectly normal
{8601}{8660}But disturbing.|And not the natural order of things
{8661}{8698}And do you think it'll happen again?
{8699}{8750}I don't know.|I should look into it
{8751}{8780}With the books
{8781}{8840}Do we have any books on this?
{8841}{8887}Well, we just gotta break it down
{8888}{8964}Look at the factors before it happens again.|Because I for one...
{8965}{8990}I've got a theory
{8991}{9020}That it's a demon
{9021}{9050}A dancing demon!
{9051}{9110}No, something isn't right there
{9111}{9194}I've got a theory|Some kid is dreamin'
{9195}{9260}And we're all stuck inside|his wacky Broadway nightmare
{9261}{9419}I've got a theory|We should work this out
{9433}{9619}It's getting eerie|What's this cheery singing all about?
{9620}{9649}It could be witches!
{9650}{9701}Some evil witches!
{9702}{9769}Which is ridiculous,|'Cause witches they were persecuted
{9770}{9887}Wicca good and love the earth|And woman power|And I'll be over here
{9888}{10019}I've got a theory!|It could be bunnies!
{10020}{10047}I've got a...
{10048}{10189}Bunnies aren't just cute|Like everybody supposes!
{10190}{10339}They've got them hoppy legs|And twitchy little noses!
{10340}{10414}And what's with all the carrots?
{10415}{10571}What do they need|Such good eyesight for anyway?
{10579}{10735}Bunnies! Bunnies!|It must be bunnies!
{10820}{10860}Or maybe midgets
{10861}{11022}I've got a theory|We should work this fast
{11025}{11215}Because it clearly could get serious|Before it's passed
{11216}{11362}I've got a theory|It doesn't matter
{11387}{11536}What can't we face|If we're together?
{11540}{11665}What's in this place|That we can't weather?
{11666}{11739}Apocalypse?
{11740}{11807}We've all been there
{11808}{11877}The same old trips
{11878}{11983}Why should we care?
{11996}{12135}What can't we do|If we get in it?
{12147}{12269}We'll work it through within a minute
{12270}{12346}We have to try
{12347}{12417}We'll pay the price
{12418}{12496}It's do or die
{12497}{12586}Hey, I've died twice
{12587}{12736}What can't we face if we're together?|What can't we face...
{12737}{12873}What's in this place that we can't weather?|... if we're together...
{12874}{13003}There's nothing we can't face
{13007}{13110}Except for bunnies
{13187}{13246}See, okay, that was disturbing
{13247}{13276}I thought it was neat
{13277}{13380}So what is it?|What's causing it?
{13381}{13456}I thought it didn't matter
{13457}{13559}Well, I'm not exactly quaking|in my stylish yet affordable boots
{13560}{13635}but there's definitely something|unnatural going on here
{13636}{13755}And that doesn't usually lead to hugs and puppies
{13756}{13875}Well, is it just us?|I mean, is it only happening to us?
{13876}{14044}'Cause that would probably mean a spell or...
{14056}{14455}They got... the mustard... out!
{14535}{14633}It's not just us
{14655}{14769}Oh my god. You will never believe|what happened at school today
{14770}{14864}Everybody started singing and dancing?
{14865}{14949}I gave birth to a pterodactyl
{14950}{15047}Oh my god, did it sing?
{15048}{15104}So, you guys too, huh?
{15105}{15179}So what'd you guys sing about?
{15180}{15224}Math
{15225}{15368}Tha... That's right! The, the volume. The text
{15369}{15434}What text?
{15435}{15600}The volume-y text. You know?|The, the report
{15614}{15673}The what now?
{15674}{15793}There's just a few volumes back at the house|that deal with mystical chants, bacchanals.
{15794}{15853}It might be relevant
{15854}{15883}Yeah, we could ...
{15884}{16003}Well, I'm a hair's breadth|from investigating bunnies at the moment|so I'm open to anything
{16004}{16123}Great, we'll go check it out|and we'll give you a call
{16124}{16213}Yeah, this could blow the whole thing wide open
{16214}{16300}Do we have any books at all at home?
{16301}{16389}Well, who wants to be cooped up on a day like this?
{16390}{16513}The sun is shining, there's songs going on...
{16514}{16571}... those guys are checking you out
{16572}{16659}What? What are they looking at?
{16660}{16722}The hotness of you, doofus
{16723}{16778}Those boys really thought I was hot?
{16779}{16825}Entirely
{16826}{16962}Oh my god. I'm cured! I want the boys!
{16963}{17082}Do I have to fight to keep you?|'Cause I'm not large with the butch.
{17083}{17235}I'm just... not used to that.|They- they were really looking at me?
{17236}{17349}And you can't imagine what they see in you
{17350}{17485}I know exactly what they see in me.|You
{17486}{17591}I lived my life in shadow
{17592}{17712}Never the sun on my face.
{17742}{17856}It didn't seem so sad, though
{17857}{17974}I figured that was my place
{17975}{18090}Now I'm bathed in light
{18102}{18221}Something just isn't right
{18222}{18324}I'm under your spell
{18325}{18371}How else could it be
{18372}{18460}Anyone would notice me?
{18461}{18574}It's magic, I can tell
{18576}{18630}How you set me free
{18631}{18741}Brought me out so easily.
{18742}{18848}I saw a world enchanted
{18849}{18978}Spirits and charms in the air
{18992}{19100}I always took for granted
{19101}{19219}I was the only one there.
{19220}{19328}But your power shone
{19331}{19460}Brighter than any I've known.
{19477}{19549}I'm under your spell
{19550}{19629}Nothing I can do
{19630}{19719}You just took my soul with you
{19720}{19809}You worked your charms so well
{19810}{19869}Finally, I knew
{19870}{19958}Everything I dreamed was true
{19959}{20151}You made me believe|Ahhh, ahhh, ahhh
{20152}{20449}Ahhh, ahhh, ahhh
{20455}{20563}The moon to the tide
{20581}{20691}I can feel you inside
{20701}{20779}I'm under your spell
{20780}{20858}Surging like the sea
{20859}{20948}Wanting you so helplessly
{20949}{21038}I break with every swell
{21039}{21098}Lost in ecstasy
{21099}{21158}Spread beneath my willow tree
{21159}{21413}You make me complete!
{21534}{21767}You make me complete!
{21770}{21807}You make me...
{21808}{21856}I bet they're not even working
{21857}{21907}Who now?
{21908}{21945}Willow and Tara.
{21946}{21991}You see the way they were with each other?
{21992}{22127}The get-a-roominess to them?|I bet they're...
{22128}{22210}... singing.|They're probably singing right now
{22211}{22284}I'm sure Willow and Tara are making every effort
{22285}{22314}Oh, yeah
{22315}{22347}Xander
{22348}{22456}Buffy, it's okay|I do know about this stuff
{22457}{22542}Besides, it's all kinda romantic
{22543}{22596}No it's not!
{22597}{22725}Come on!|Songs, dancing around. What's gonna be wrong with that?
{23547}{23655}That's entertainment
{23706}{23795}You want some breakfast, baby?
{23796}{23855}You don't have to go to work?
{23856}{23917}Nah, I shut the crew down for the day
{23918}{24031}My guys start dancing around me,|I don't know if I can deal
{24032}{24099}It's a flab thing
{24100}{24185}So, waffles?
{24186}{24275}Will you still make me waffles|when we're married?
{24276}{24484}No, I'll only make them for myself, but|by California law, you will own half of them
{24485}{24574}Hey, how about omelettes?|I could do an omelette. I've almost got that...
{24575}{24764}This is the man that I plan to entangle|Isn't he fine?
{24785}{24897}My claim to fame was to maim and to mangle
{24898}{24994}Vengeance was mine!
{24995}{25084}But I'm out of the biz
{25085}{25204}The name I made, I'll trade for his
{25205}{25310}The only trouble is
{25321}{25417}I'll never tell
{25444}{25533}She is the one|She's such wonderful fun
{25534}{25647}Such passion and grace
{25654}{25780}Warm in the night when I'm right in her tight|... Embrace!
{25781}{25833}Tight embrace!
{25834}{25944}I'll never let her go
{25954}{26043}The love we've known can only grow
{26044}{26163}There's just one thing that - no
{26164}{26253}I'll never tell
{26254}{26386}'Cause there's nothing to tell
{26493}{26552}He snores|She wheezes
{26553}{26603}Say 'housework' and he freezes
{26604}{26702}She eats these skeezy cheeses that I can't describe
{26703}{26763}I talk, he breezes
{26764}{26818}She doesn't know what pleases
{26819}{26912}His penis got diseases from a Chumash tribe!
{26913}{27038}The vibe gets kind of scary
{27125}{27176}Like she thinks I'm ordinary
{27177}{27230}Like it's all just temporary
{27231}{27284}Like her toes are kind of hairy
{27285}{27332}But it's all very well
{27333}{27451}'Cause god knows, I'll never tell!
{27452}{27505}"MAYHEM CAUSED. MONSTERS CERTAINLY|NOT INVOLVED, OFFICIALS SAY"
{27506}{27541}When things get rough
{27542}{27601}He just hides behind his Buffy!
{27602}{27655}Now look, he's getting huffy
{27656}{27722}'Cause he knows that I know
{27723}{27772}She clings|She's needy
{27773}{27823}She's also really greedy
{27824}{27871}She nev..|- His eyes are beady!
{27872}{27991}This is my verse, hello! She...
{27992}{28124}Look at me! I'm dancing crazy!
{28831}{28917}You know...
{28919}{28971}You're quite the charmer
{28972}{29040}My knight in armor
{29041}{29085}You're the cutest of the Scoobies
{29086}{29130}With your lips as red as rubies
{29131}{29284}And your firm yet supple|Tight embrace!
{29632}{29686}He's swell|She's sweller
{29687}{29729}He'll always be my feller
{29730}{29849}That's why I'll never tell her that I'm petrified
{29850}{29909}I've read this tale
{29910}{29969}There's wedding, then betrayal
{29970}{30059}I know there'll come the day|I'll want to run and hide
{30060}{30134}I lied
{30150}{30248}I said it's easy
{30264}{30348}I've tried
{30358}{30478}But there's these fears I've can't quell
{30479}{30568}Is she looking for a pot of gold?
{30569}{30688}Will I look good when I've gotten old?
{30689}{30778}Will our lives become too stressful|if I'm never that successful?
{30779}{30868}When I get so worn and wrinkly|that I look like David Brinkley?
{30869}{30928}Am I crazy?|Am I dreamin'?
{30929}{30958}Am I marrying a demon?
{30959}{31078}We could really raise the beam|in making marriage a hell!
{31079}{31138}So, thank god, I'll never tell!
{31139}{31268}I swear that I'll never tell!
{31289}{31378}My lips are sealed
{31379}{31467}I take the Fifth
{31468}{31557}Nothing to see|Move it along
{31558}{31656}I'll never Tell!
{31708}{31767}It's a nightmare|It has to be stopped
{31768}{31827}It's a plague.|It's like a nightmare about a plague.
{31828}{31857}It was like we were being watched
{31858}{31887}- It's like, I didn't wanna be saying things...|- Like there was a wall missing...
{31888}{31927}- ... but they just kept pouring out|- ... in our apartment
{31928}{31953}And they rhymed and they were mean and
{31954}{32001}Like there were only three walls and not a fourth wall and
{32002}{32028}- My eyes are not beady!|- My toes are not hairy!
{32029}{32073}Giles, you've got to stop it
{32074}{32157}Well, I am looking into some leads, and I...
{32158}{32217}It's just, clearly our number is a retro pastiche
{32218}{32277}that's never going to be a breakaway pop hit
{32278}{32307}Work with me, British man
{32308}{32367}Give me an axe and show me where to point it.
{32368}{32426}Well now, Xander, it's not quite that simple
{32427}{32541}But I have learned about some disturbing things. Basically...
{32542}{32726}I'm asking you please no|It isn't right, it isn't fair
{32727}{32816}There was no parking anywhere
{32817}{32899}I think that hydrant wasn't there
{32900}{33017}Why can't you let it go?
{33022}{33056}I think I've paid more than my share...
{33057}{33146}As in burnt up?|Somebody set people on fire? That's nuts!
{33147}{33206}I don't know
{33207}{33295}One more verse of our little ditty|and I would've been looking for a gas can
{33296}{33360}Well, clearly emotions are running high
{33361}{33543}But as far as I can tell these people|burnt up from the inside, spontaneously combusted
{33544}{33586}I've only seen the one
{33587}{33685}I was able to examine the body while|the police were taking witness arias
{33686}{33710}Okay, but we're sure
{33711}{33805}That the things are related: the singing|and dancing, and burning and dying
{33806}{33865}We're not sure of much
{33866}{33985}Buffy's looking for leads at the local demon haunts
{33986}{34105}At least ... in theory she is,|but... she doesn't seem to...
{34106}{34165}She's easing back into it
{34166}{34255}We pulled her out of an untold hell dimension
{34256}{34405}Ergo the weirdness|The important thing is to be there for her
{34406}{34571}I'm helping her as much as I can, but, uh...
{34825}{34944}The sun sets and she appears
{34945}{35004}Come to serenade me?
{35005}{35064}So you know what's going on
{35065}{35154}Well, I've seen some damn funny|things in the last two days
{35155}{35304}A 600 pound Chirago demon making like|Yma Sumac, that one will stay with you
{35305}{35389}I remain immune, happy to say
{35390}{35426}Drink?
{35427}{35513}A world of no
{35514}{35633}So any idea what's causing this?
{35634}{35723}Oh. So that's all
{35724}{35783}You've just come to pump me for information
{35784}{35843}What else would I wanna pump you for?
{35844}{35933}I really just said that, didn't I?
{35934}{36083}Yeah, well...|don't wanna bore you with the small talk
{36084}{36173}Don't know a thing
{36174}{36233}What's up? You're all bad moody
{36234}{36368}Nothing. Glad you could stop by
{36384}{36422}It's nothing
{36423}{36495}What?
{36510}{36627}I died|So many years ago
{36698}{36856}But you can make me feel|Like it isn't so
{36863}{37012}And why you come to be with me|I think I finally know
{37013}{37092}Mmm, mmm
{37133}{37284}You're scared|Ashamed of what you feel
{37308}{37461}And you can't tell the ones you love|You know they couldn't deal
{37462}{37644}Whisper in a dead man's ear|It doesn't make it real
{37732}{37791}That's great
{37792}{37881}But I don't wanna play
{37882}{38031}'Cause being with you touches me|More than I can say
{38032}{38211}But since I'm only dead to you|I'm saying stay away
{38212}{38329}And let me rest in peace
{38332}{38480}Let me rest in peace|Let me get some sleep
{38481}{38630}Let me take my love and bury it|In a hole six foot deep
{38631}{38812}I can lay my body down|But I can't find my sweet release
{38813}{38930}So let me rest in peace!
{38931}{39075}You know|You've got a willing slave
{39083}{39200}And you just love to play the thought|That you might misbehave
{39201}{39390}But till you do I'm telling you|Stop visiting my grave
{39395}{39509}And let me rest in peace
{39510}{39613}I know|I should go
{39650}{39799}But I follow you|Like a man possessed
{39800}{39919}There's a traitor here|Beneath my breast
{39920}{40066}And it hurts me more|Than you've ever guessed
{40067}{40208}If my heart could beat,|It would break my chest
{40209}{40342}But I can see|You're unimpressed
{40343}{40407}So leave me be
{40408}{40547}And let me rest in peace|Let me get some sleep
{40548}{40698}Let me take my love and bury it|In a hole six foot deep
{40699}{40874}I can lay my body down|But I can't find my sweet release...
{40875}{40965}Let me rest in peace
{40966}{41110}Why won't you|Let me rest in peace?
{41417}{41549}So... you're not staying then?
{41640}{41687}Lotta homework?
{41688}{41849}Ah, math. It seemed cool|when we were singing about it.
{41850}{41939}Willow said they have a lead on|the whole musical extravaganza evil
{41940}{42077}This demon that can be summoned,|some sort of Lord of the Dance
{42078}{42167}But not the scary one. Just a demon
{42168}{42257}Do they know who summoned it?
{42258}{42332}They don't even know its name yet|But Willow will find out
{42333}{42406}She's the brainy type
{42407}{42484}I'm glad you guys made up
{42485}{42526}What?
{42527}{42609}That fight you guys had|about magic and stuff?
{42610}{42706}It gives me belly rumblings|when you guys fight.
{42707}{42785}Dawn, Willow and I never fought about...
{42786}{42856}It's okay. It's just...
{42857}{43006}.. you guys are so great together.|I just hate it when you...
{43007}{43114}But that was the only fight|I've seen you guys have anyway
{43115}{43241}But I'm still glad it's over.
{43242}{43276}Dawn, I, um...
{43277}{43425}... there's something I need at the shop.|Will you be okay for a little while?
{43426}{43545}Yes. The fifteen-year-old can spend|a half an hour alone in her locked house
{43546}{43666}I won't be gone long
{44640}{44760}Does anybody even notice?
{44872}{44987}Does anybody even care?
{47772}{47945}Why'd you run away?|Don't you like my... style?
{48012}{48101}Why don't you come and play?|I guarantee a...
{48102}{48207}... great big smile
{48252}{48371}I come from the imagination
{48372}{48490}And I'm here strictly|by your invocation
{48491}{48661}So what do you say?|Why don't we dance awhile?
{48731}{48889}I'm the hot swing|I'm the twist and shout
{48971}{49146}When you gotta sing|When you gotta... let it out
{49181}{49300}You call me and I come a-running
{49301}{49449}I turn the music on|I bring the fun in
{49450}{49618}Now we're partyin'|That's what it's all about
{49660}{49806}'Cause I know... what you feel, girl
{49900}{50034}I know just what you feel, girl
{50144}{50259}So... you're like a good demon?|Bringing the fun in?
{50260}{50330}All these melodies...
{50331}{50436}They go on too long
{50525}{50576}Then that energy
{50577}{50714}Starts to come on way too strong
{50739}{50858}All those hearts laid open,|That must sting
{50859}{50978}Plus, some customers|just start combusting
{50979}{51038}That's the penalty
{51039}{51154}When life is but a song
{51219}{51344}You brought me down into this town
{51345}{51463}So, when we blow this scene
{51464}{51584}Back we will go to my kingdom below
{51585}{51702}And you will be my queen
{51721}{51817}'Cause I know what you feel, girl
{51818}{51937}No, you see, You and me|Wouldn't be very regal
{51938}{52051}I'll make it real, girl
{52052}{52177}What I mean, I'm fifteen|So this queen thing's illegal
{52178}{52297}I can bring whole cities to ruin
{52298}{52416}And still have time to get a soft-shoe in
{52417}{52536}Well, that's great, but I'm late|And I'd hate to delay her
{52537}{52656}Something's cooking, I'm at the griddle
{52657}{52769}I bought Nero his very first fiddle
{52770}{52929}She'll get pissed, if I'm missed|See, my sister's the Slayer
{52930}{52956}The Slayer?
{52957}{53043}Yuh... huh.
{53047}{53166}Find her.|Tell her... tell her everything.
{53167}{53344}Just get her here.|I want to see the Slayer burn.
{53347}{53578}Now we're partying. That's what it's all about
{53646}{53705}Good. Good.
{53706}{53795}I feel like I should... bow,|or... have honor or something.
{53796}{53855}It may seem hookey, but we need to work on precision
{53856}{53939}And concentration as much as power.
{53940}{53998}We're still not sure what we're facing.
{53999}{54035}Oh, you'll figure it out.
{54036}{54185}I'm just worried this whole session's gonna|turn into some training montage from an 80's movie.
{54186}{54277}Ah. Well, if we hear any inspirational power chords
{54278}{54388}we'll just lie down until they go away
{54389}{54484}I don't think we need to work that much on your strength
{54485}{54626}Yeah, I'm pretty spry for a corpse
{54635}{54814}Have you spoken to Dawn about that incident at Halloween?
{54815}{54904}Oh. I thought you took care of that
{54905}{54964}Right
{54965}{55086}What would I do without you?
{55087}{55174}Okay. I'm ready
{55175}{55326}You're not ready|For the world outside
{55355}{55518}You keep pretending|But you just can't hide
{55543}{55683}I know I said that|I'd be standing by your side
{55684}{55763}But I...
{55894}{56050}Your path's unbeaten|And it's all uphill
{56074}{56225}And you can meet it|But you never will
{56254}{56413}And I'm the reason|That you're standing still
{56414}{56493}But I...
{56553}{56672}I wish I could say the right words
{56673}{56732}To lead you through this land
{56733}{56860}Wish I could play the father
{56862}{56912}And take you by the hand
{56913}{57026}Wish I could stay here
{57035}{57122}But now I understand
{57123}{57238}I'm standing in the way
{57303}{57464}The cries around you|You don't hear at all
{57482}{57643}'Cause you know|I'm here to take that call
{57662}{57831}So you just lie there|When you should be standing tall
{57832}{57911}But I...
{57982}{58104}I wish I could lay your arms down
{58105}{58171}And let you rest at last
{58172}{58291}Wish I could slay your demons
{58292}{58350}But now that time has passed
{58351}{58464}Wish I could stay here
{58471}{58530}Your stalwart, standing fast
{58531}{58670}But I've been standing in the way
{58711}{58845}I'm just standing... in the way
{58891}{59016}Did you just say something?
{59161}{59295}"Lethe's Bramble. Used for augmenting|spells of forgetting and mind control. "
{59296}{59457}I'm under your spell|God, how can this be?
{59494}{59602}Playing with my memory
{59603}{59729}You know I've been through hell
{59730}{59808}Willow, don't you see?
{59809}{59899}There'll be nothing left of me
{59900}{59999}You made me believe...
{60000}{60192}You made me believe...|... believe me, I don't wanna go
{60201}{60357}And it'll grieve me|'Cause I love you so
{60409}{60507}But we both know
{60509}{60674}- Wish I could say the right words|- Wish I could trust that it was just this once
{60675}{60748}- To lead you through this land|- But I must do what I must
{60749}{60868}- Wish I could play the father|- I can't adjust to this disgust
{60869}{60958}- And take you by the hand|- We're done and I just
{60959}{61548}Wish I could stay
{61587}{61695}Wish I could stay...
{61888}{61947}Lookie lookie what I found
{61948}{62029}Is... is this the demon guy?
{62030}{62067}Tara!
{62068}{62127}Works for him
{62128}{62219}Has a nice little story|for the Slayer, don't you?
{62220}{62323}Come on, then|Sing
{62443}{62559}My master has the Slayer's sister hostage|at the Bronze because she summoned him
{62560}{62669}and at midnight he's going to take her|to the underworld to be his queen
{62670}{62729}What does he want?
{62730}{62782}Her
{62783}{62932}If that's all you've got to say, then
{62937}{63056}Strong|Someday he'll be a real boy
{63057}{63176}So. Dawn's in trouble|Must be Tuesday
{63177}{63236}I... I just left her for a few minutes
{63237}{63358}Oh, it's not your fault. So what's the plan?
{63359}{63415}Plan, schman. Let's mount up.
{63416}{63470}No
{63471}{63555}Uh, Dawn may have had the wrong idea|in summoning this creature, but...
{63556}{63625}I've seen some of these|underworld child bride deals
{63626}{63745}and, and they never end well.|Well, maybe once
{63746}{63805}We're not just gonna stay here
{63806}{63892}Yes we are.
{63917}{63955}Buffy's going alone
{63956}{64070}Gah! Don't be a stupid git. There is no...
{64071}{64165}If I want your opinion, Spike, I'll...
{64166}{64225}I'll never want your opinion
{64226}{64259}A little confusion spell could...
{64260}{64404}No!|I mean, I don't think it'll help
{64405}{64494}Look, forget them, Slayer.|I've got your back
{64495}{64582}I thought you wanted me to stay away from you
{64583}{64644}Isn't that what you sang?
{64645}{64699}Spike sing a widdle song?
{64700}{64792}Would you say it was a breakaway pop hit|or more of a book number?
{64793}{64824}Let it go, sweetie.
{64825}{64949}Fine. I hope you dance till you burn.
{64950}{65063}You and the little bit
{65215}{65304}You're really not coming
{65305}{65363}It's up to you, Buffy
{65364}{65423}What do you expect me to do?
{65424}{65506}Your best
{65784}{65925}I touch the fire and it freezes me
{65966}{66095}I look into it and it's black
{66114}{66287}Why can't I feel?|My skin should crack and peel
{66294}{66404}I want the fire back!
{66443}{66592}Now through the smoke,|She calls to me
{66593}{66727}To make my way across the flame
{66743}{66884}To save the day|Or maybe melt away
{66893}{67013}I guess it's all the same
{67013}{67147}So I will walk through the fire
{67163}{67282}'Cause where else can I turn?
{67283}{67410}I will walk through the fire
{67432}{67491}And let it...
{67492}{67629}The torch I bear is scorching me
{67642}{67761}Buffy's laughing,|I've no doubt
{67762}{67911}I hope she fries|I'm free if that bitch dies!
{67912}{68001}I better help her out
{68002}{68136}'Cause she is drawn to the fire
{68182}{68301}Some people never learn|She will never learn
{68302}{68420}And she will walk through the fire
{68421}{68480}And let it...
{68481}{68630}Will this do a thing to change her?|Am I leaving Dawn in danger?
{68631}{68750}Is my slayer too far gone to care?
{68751}{68840}What if Buffy can't defeat it?
{68841}{69050}Beady Eyes is right, we're needed!|Or we could just sit around and glare
{69051}{69170}We'll see it through|It's what we're always here to do
{69171}{69308}So we will walk through the fire
{69350}{69469}So one by one, they turn from me
{69470}{69619}I guess my friends can't face the cold|"What can't we face... "
{69620}{69769}But why I froze, not one among them knows|"If we're together? "
{69770}{69880}And never can be told
{69890}{69979}She came from the grave much graver|"So one by one they turn to me"
{69980}{70039}First he'll kill her, then I'll save her
{70040}{70179}Everything is turning out so dark|"Going through the motions... "
{70180}{70249}No, I'll save her, then I'll kill her|"Walking through the part"
{70250}{70336}I think this line's mostly filler|"Ain't what they had in mind"
{70337}{70458}What's it gonna take to strike a spark?|"It's what they have inside"
{70459}{70584}These endless days are finally ending in a blaze|"She will come to me"
{70585}{70714}And we are caught in the fire
{70729}{70818}The point of no return
{70819}{71101}So we will walk through the fire|And let it burn
{71112}{71440}Let it burn!
{71486}{71568}Showtime!
{71718}{71777}I love a good entrance.
{71778}{71910}How are you with death scenes?
{71928}{71987}You got a name?
{71988}{72047}I've got a hundred
{72048}{72137}Well, I ought to know what to call you|if you're gonna be my brother-in-law
{72138}{72200}Buffy, I swear I didn't do it
{72201}{72346}Don't worry.|You're not going anywhere. I am
{72347}{72376}What?
{72377}{72496}Deal's this. I can't kill you?
{72497}{72586}Let it burn! You take me to Hellsville in her place
{72587}{72646}What if I kill you?
{72647}{72706}Trust me. Won't help
{72707}{72766}Hm, that's gloomy!
{72767}{72826}That's life
{72827}{73036}Come now, is that really what you feel?|Isn't life a miraculous thing?
{73037}{73126}I think you already know
{73127}{73276}Life's a show|And we all play our parts
{73277}{73395}And when the music starts
{73396}{73506}We open up our hearts
{73516}{73575}It's all right
{73576}{73695}If some things come out wrong
{73696}{73811}We'll sing a happy song
{73816}{73929}And you can sing along
{73936}{73995}Where there's life|There's hope
{73996}{74055}Every day's|A gift
{74056}{74115}Wishes can|Come true
{74116}{74175}Whistle while|You work
{74176}{74235}So hard|All day
{74236}{74349}To be like other girls
{74355}{74496}To fit in in this glittering world
{74535}{74594}Don't give me songs
{74595}{74654}She needs backup. Anya, Tara
{74655}{74760}Don't give me songs
{74805}{74963}Give me something to sing about|Ahhhhh...
{75135}{75291}I need something to sing about|Ahhhhh...
{75614}{75763}Life's a song|You don't get to rehearse
{75764}{75877}And every single verse
{75884}{76003}Can make it that much worse
{76004}{76160}Still my friends|Don't know why I ignore
{76184}{76303}The million things or more
{76304}{76419}I should be dancing for
{76423}{76482}All the joy|Life sends
{76483}{76542}Family|And friends
{76543}{76602}All the twist|And bends
{76603}{76662}Knowing that|It ends
{76663}{76722}Well that|Depends
{76723}{76833}On if they let you go
{76843}{76975}On if they know enough to know
{77023}{77136}That when you've bowed
{77143}{77248}You leave the crowd
{77622}{77711}There was no pain
{77712}{77771}No fear, no doubt
{77772}{77911}Till they pulled me out|Of Heaven
{78042}{78131}So that's my refrain
{78132}{78191}I live in Hell
{78192}{78281}'Cause I've been expelled
{78282}{78340}From Heaven
{78341}{78456}I think I was in Heaven
{78551}{78692}So give me something to sing about
{78791}{78916}Please|Give me something...
{79810}{79911}Life's not a song
{79939}{79989}Life isn't bliss
{79990}{80079}Life is just this
{80080}{80166}It's living
{80260}{80358}You'll get along
{80379}{80468}The pain that you feel
{80469}{80594}You only can heal|By living
{80679}{80799}You have to go one living
{80799}{80912}So one of us is living
{81039}{81231}The hardest thing in this world...|... is to live in it
{81368}{81464}Now that was a show-stopping number
{81465}{81529}Not quite the fireworks that I was looking for
{81530}{81577}Get out of here
{81578}{81681}Mmm, I smell power
{81696}{81787}I guess the little missus and|I should be on our way
{81788}{81847}That's never going to happen
{81848}{81967}I don't make the rules.|She summoned me.
{81968}{82069}I so did not. He keeps saying that
{82070}{82147}You have my talisman on, sweet thing
{82148}{82326}Oh, but, no, I, I, um, uh, this|at, at the Magic Box, on the floor
{82327}{82386}I was, I was cleaning
{82387}{82476}and I... forgot... but...|I didn't summon anything
{82477}{82566}Well now, that's a twist
{82567}{82656}If it was in the shop...
{82657}{82789}... then one of us probably...
{82867}{82896}Xander?!
{82897}{82956}Well, I didn't know what was gonna happen!
{82957}{83046}I just thought there were|gonna be dances and songs
{83047}{83109}I just wanted to make sure we'd...
{83110}{83226}... we'd work out|Get a happy ending
{83227}{83380}I think everything worked out just fine
{83406}{83533}Does this mean that I have to...
{83534}{83569}... be your queen
{83570}{83645}It's tempting
{83646}{83765}But I think we'll waive|that clause just this once
{83766}{83855}Big smiles everyone!
{83856}{83945}You beat the bad guy
{83946}{84005}What a lot of fun
{84006}{84135}You guys have been real swell
{84216}{84275}And there's not a one
{84276}{84401}Who can say this ended well
{84455}{84574}All those secrets you've been concealing
{84575}{84664}Say you're happy now
{84665}{84724}Once more with feeling
{84725}{84784}Now I gotta run
{84785}{84874}See you all...
{84875}{85157}... in heeeeeeell!
{85564}{85691}Where do we go... from here?
{85810}{85937}Where do we go... from here?
{86014}{86103}The battle's done|And we kind of won
{86104}{86233}So we sound our victory cheer
{86254}{86374}Where do we go from here?
{86493}{86608}Why is the path unclear
{86703}{86825}When we know home is near?
{86913}{87002}Understand we'll go hand in hand
{87003}{87102}But we'll walk alone in fear
{87103}{87152}Tell me!
{87153}{87273}Where do we go from here?
{87362}{87482}When does the end appear?
{87542}{87601}Bugger this
{87602}{87727}When do the trumpets cheer?
{87786}{87884}The curtains close on a kiss, god knows
{87885}{87969}We can tell the end is near
{87970}{88084}Hey|"Where do we go from here? "
{88085}{88141}You should go back inside
{88142}{88261}Finish the big group sing|Get your kum-ba-yayas out
{88262}{88349}I don't want to
{88350}{88407}The day you suss out what you do want
{88408}{88440}There'll probably be a parade
{88441}{88560}Seventy- six bloody trombones
{88561}{88620}- Spike...|- Look, you don't have to say anything
{88621}{88762}I touch the fire and it freezes me
{88771}{88830}I died...
{88831}{89010}- I look into it and it's black|- So many years ago
{89011}{89067}This isn't real
{89068}{89130}This isn't real|But you can make me
{89131}{89268}- But I just want to feel|- Feel
{89308}{89428}Where do we go from here?
{89460}{89769}THE END