{25}{25}movie info: 25fps|/SubEdit b. 3850 (http://alfa. icis. pcz. czest. pl/~subedit)/
{25}{100}- Previously.|- You never had it so good as me.
{100}{175}If you tell anyone about last night,|I will kill you.
{175}{275}So you three have, what,|banded together to be pains in my ass?
{300}{375}We're your arch nemesises...ses.
{375}{450}You mighùve beaten us this time,|Slayer, but next time...
{450}{550}Maybe not!
{600}{675}- Amy? How've you been?|- Rat. You?
{675}{700}- Dead.|- Oh.
{700}{800}Iùs nice having another|magically inclined friend around.
{800}{875}Iùs too early to go home yet.|What Ôyou wanna do?
{875}{925}- I have a better idea.|- Is it dangerous?
{925}{1000}Leùs get outta here.
{1000}{1075}Dawnie, I'm sorry. I'm so...
{1075}{1150}- You coulÔve killed her.|- I need help.
{1150}{1200}No more spells. I'm finished.
{1200}{1275}There's some money stuff|we have to talk to you about.
{1275}{1300}You're telling me I'm broke?
{1300}{1375}- How bad is it?|- Anya says pretty bad.
{1375}{1475}Buffy, some discussion about...|what you're gonna do now.
{1500}{1600}I've been giving that a lot of thought,|actually, and I think I've figured it out.
{1675}{1775}I get Warren being the super- villainy type,|but I thought Jonathan learned that lesson.
{1800}{1850}I've never heard of this other guy.
{1850}{1950}You should have seen their headquarters.|It was like the nerd natural habitat.
{1975}{2025}If we know where they are,|leùs do something.
{2025}{2100}We tried. Buffy was gonna go in|and bust 'em on the spot.
{2100}{2175}- I'm sensing a "not so completely".|- She went in and...
{2175}{2275}Speaking of Buffy, isn't she ready?|She'll be late for her first day.
{2275}{2350}Hey, respect the narrative flow much?
{2350}{2425}Please continue the story of failure.
{2425}{2475}So Buffy went in, but they'd cleared out.
{2475}{2575}And then she brought back the stuff that they|left. some spell books, some parchments,
{2625}{2725}a couple of rare things -|charmed objects and a conjurer's harp.
{2775}{2875}And they had other stuff. Razor scooters,|pictures of the Vulcan woman on Enterprise.
{2900}{2975}Ooh!
{2975}{3025}I mean...nerds.
{3025}{3125}OK. See, this is why demons|are better than people.
{3125}{3175}Interesting turn.
{3175}{3250}When I was a vengeance demon|I caused pain and mayhem, certainly.
{3250}{3350}But I put in a full day's work doing it|and I got compensated appropriately.
{3375}{3450}Welcome to today's episode of|Go, Money! Go! I hear it daily.
{3450}{3525}Yep, for the rest of your life.
{3525}{3625}But supervillains want reward without labour|to make things come easy. Iùs wrong.
{3650}{3750}Without labour there can be no payment,|and vice versa. The country cannot progress.
{3750}{3825}The workers are the tools that shape America.
{3825}{3900}Good to know.
{3900}{4000}I was kind of feeling like a tool.|And now I know why.
{5350}{5425}You've seen us|in your city or small town,
{5425}{5500}ordered delicious food|from our happy employees.
{5500}{5575}But now you're seeing it all in a new way|from behind the counter.
{5575}{5650}You've just become part of|the Double Meat experience!
{5650}{5700}I'm part of it.
{5700}{5800}- I'm part of it.|- I'm a part of it, too.
{5800}{5900}This cow and chicken don't know it yet, but|they're destined to become part of it as well.
{5925}{6025}So what happens when a cow and a chicken|get together? Thaùs a Double Meat Medley!
{6025}{6125}Leùs take a look now at the process|of harvesting these two special meats.
{6300}{6400}Holy crap!
{6400}{6475}..washing your hands|after each visit to the restroom.
{6475}{6575}Follow these rules and you'll be a happy part|of the Double Meat family for a long time!
{6700}{6775}- Interesting, isn't it?|- Oh, yes!
{6775}{6875}Like how the cow and the chicken come|together even though they've never met.
{6875}{6975}Iùs like Sleepless in Seattle|if Meg and Tom were, like, minced.
{7050}{7125}I'm Manny the manager.|Iùs not a joke. Iùs just my name.
{7125}{7225}Right. You mentioned that a couple of times|when I filled out the application.
{7225}{7275}Why do you want to work here, Buffy?
{7275}{7350}You seem like a sharp woman|and there are a lot of other jobs.
{7350}{7450}I kinda need money pretty quickly, like, today,|so I didn't want a lengthy interview process.
{7500}{7600}And I figured this was|probably the fastest...way...to...
{7600}{7700}Because I...wanted to be part|of the Double Meat experience?
{7700}{7750}Hm.
{7750}{7825}Come on, leùs take a tour.
{7825}{7925}Phillip, Timothy, this is Buffy.|She's gonna work the counter.
{7925}{7975}Hi.
{7975}{8025}What happened to the other one? Katherine?
{8025}{8100}- Emily?|- Yeah.
{8100}{8150}She's gone.
{8150}{8225}What happened?
{8225}{8325}Whatever always happens.
{8350}{8450}- You can use this one.|- There's someone's stuff in there.
{8475}{8550}They must have left it.|You can toss it or keep what you want.
{8550}{8650}- Sure they're not coming back?|- We have a lot of turnover here.
{8700}{8800}- Watch these two.|- Are they gonna do something?
{8800}{8875}They're solid. Follow their example|and you won't go wrong.
{8875}{8925}- They're lifers.|- Lifers?
{8925}{9025}In it for life, like me. You wanna get|something out of this, you'll do the same.
{9050}{9150}You put the work in, and 10 years from now|you'll be where I am, I promise you.
{9300}{9400}Congratulations. You're on the clock.
{9475}{9575}This is the kitchen -|the beating heart of the Double Meat Palace.
{9675}{9700}Wow.
{9700}{9775}- They're all so...identical.|- Yeah.
{9775}{9850}They all start to look the same to me, too.
{9850}{9950}Oh, no, not the employees.|The chicken slices.
{10150}{10225}Yeah. Medley Meal number two -|double- size it.
{10225}{10325}Drive- through's over there. High- pressure|job. You won't need to go in there.
{10350}{10450}Over there's the grill, the fryers, the walk- in|freezer. You don't need to go in there either.
{10550}{10625}Thaùs the dehydrated- pickle storage.
{10625}{10675}Those are locked.
{10675}{10775}Now I wanna show you this.
{10800}{10900}Look. The Double Meat Medley.
{10950}{11050}Oh, I know the Medley. Iùs just the video|was kind of graphic with the slaughter.
{11100}{11200}A classic double- decker with a twist -|a pure beefy patty above the mid- bun
{11200}{11275}and a slice of processed chicken product|below the mid- bun.
{11275}{11350}Plus pickles and the secret ingredient.
{11350}{11450}- Eat it.|- Oh, you know, I had a big breakfast.
{11450}{11550}I'll just wait for...
{11550}{11575}Oh...
{11575}{11675}But it smells so good.
{11800}{11850}Mm.
{11850}{11900}So what is the secret ingredient?
{11900}{11950}Iùs a meat process.
{11950}{12050}Now I think iùs time to start earning|your money, don't you, Buffy?
{12075}{12150}Mm- hm.
{12150}{12250}Whaùs the deal with Manny the manager?|And can I write a children's book called that?
{12250}{12325}- Fill this while I get the fries.|- Fill this?
{12325}{12425}I didn't know there was gonna be|drug testing on this job.
{12425}{12475}You're funny. You better stop that.
{12475}{12550}- Why?|- Productivity. One of Manny's watchwords.
{12550}{12650}"Levity is the time thief|that picks the pocket of a company."
{12650}{12750}I prefer "Manny's a humourless dolt who|picks the pocket of he- should- bite- me."
{12750}{12850}You really need to be quiet with that.
{12850}{12925}- Here you go.|- Thanks.
{12925}{13025}I'd like a small coffee and cherry pie.
{13075}{13125}Thaùs $1. 92, ma'am.
{13125}{13200}You hit so many buttons,|it was like button- palooza.
{13200}{13300}No, iùs easy. Look. There are little pictures|of the food on the buttons.
{13300}{13400}I hit the coffee button, then I hit|the small button and then cherry pie.
{13425}{13500}- There's a picture of a little fried pie.|- Uh- huh.
{13500}{13600}Then I hit the total button, put the money in|the drawer, close it and it resets the system.
{13625}{13675}A cocker spaniel could do it.
{13675}{13775}Why don't you take the next one,|the family? They're regulars.
{13775}{13875}- Hi. I'm new.|- I come here every day.
{13875}{13975}- Thaùs nice.|- Oh, you really might make it, dear.
{13975}{14075}Not like some of them,|where suddenly you never see them again.
{14075}{14175}- I can see you here for a long time.|- Thaùs great.
{14225}{14325}Thank you.
{14325}{14400}Hi. Welcome to the Double Meat Palace.|May I help you?
{14400}{14475}Two number four Medley Meals,|a Junior Medley,
{14475}{14525}a Fisherman's Medley and a KiÔs Meal.
{14525}{14625}Plus three fries, a chocolaty shake|and extra pickles on one of the Medleys.
{14700}{14800}Excuse me. This button -|does it look chocolaty to you?
{15525}{15550}You don't need to be in there.
{15550}{15625}Sorry. I was just curious.
{15625}{15725}Curiosity killed the cat.
{15750}{15850}Theory number five. cat burgers.
{16000}{16025}Hey, Buffy!
{16025}{16100}We're supporting|your subsistence- level work. Bravo.
{16100}{16150}Thank you. This is cool of you guys.
{16150}{16225}So, Buff, how's it going?
{16225}{16325}I don't know. I've waitressed before,|but this is different.
{16325}{16425}- When have you waitressed?|- That summer in LA.
{16425}{16525}It was a diner and we had, you know,|lots of people who didn't tip,
{16525}{16625}and funny, funny health- code violations|but...it wasn't like it is here.
{16650}{16700}I think there's something wrong here.
{16700}{16800}- Will, are you OK?|- Sorry, I...Yeah. Something's wrong?
{16850}{16925}There's this manager, right.
{16925}{17025}He's all scary and mysterious, you know.|And there's the secret ingredient.
{17025}{17125}And the people that work here,|they're kind of strange, you know.
{17125}{17225}They just stare into space,|plus they disappear.
{17225}{17300}- Disappear "poof"?|- No, not "poof'. Well, I don't think so.
{17300}{17400}Iùs fast food.|I have swum these murky waters, my friend.
{17400}{17500}There's the assorted creepiness, staring,|the enthusiastic not- showing- up- at- all.
{17525}{17600}You're seeing demons where there's just life.
{17600}{17700}I didn't say demons. Iùs just a vibe.|You guys still haven't seen this manager.
{17725}{17825}Well, isn't that him over there|getting the pickles wet?
{17825}{17900}- With the saddle shoes?|- And glasses?
{17900}{18000}Maybe iùs just the video that creeped me out,|with the cow and chicken all swirly together.
{18025}{18100}Mm, make me hungry, why don't you?
{18100}{18200}How's about one of those|delicious Medley Meals?
{18200}{18275}OK, you got it. On me.
{18275}{18325}Hey, thanks!
{18325}{18425}She'll be fine once she settles into|the routine. And by ordering, I'm helping.
{18425}{18500}- Getting a free meal?|- Well, yeah.
{18500}{18575}If you like the food here,|maybe we should get it for the reception.
{18575}{18675}- You're serving burgers? Cool!|- Well, time is running very short.
{18700}{18800}After Willow gave us the engagement party,|I figured she'd help,
{18800}{18875}but now thaùs all been blown to hell.
{18875}{18950}Hey, standing right here.|Standing right exactly here.
{18950}{19050}Sorry. Didn't mean to tempt you.
{19050}{19100}Everyone's so delicate.
{19100}{19175}Anyway, I still have to select|the bridesmaids' dresses.
{19175}{19250}Then there are the guests|from the demon realm.
{19250}{19325}You wouldn't believe|how many have yet to let us know.
{19325}{19425}- There you go, and I double- sized it for ya.|- Oh, thank you!
{19450}{19525}And cut way back on the cat.
{19525}{19625}- Cat?|- Just kidding.
{19625}{19725}Probably.
{19875}{19975}Slow night.
{20050}{20125}Gina.
{20125}{20200}Since iùs slow, you think|they'll mind if I take another break?
{20200}{20300}We're not allowed. Downtime robs us all.
{20300}{20400}Hm, thus quoth Manny. There's no one here.
{20400}{20500}Sure there is. Look.
{20550}{20625}This'll make my day complete.
{20625}{20725}- What?|- Whaùs in the Double Meat nuggets?
{20725}{20775}I'm working. Go away.
{20775}{20875}Yeah, and you chose to be in the consumer|service profession, and I'm a consumer.
{20875}{20975}- Service me.|- Order something or go.
{21000}{21100}Give a bloke a chance for his eyes to adjust.|Damn fluorescent lights make me look dead.
{21150}{21225}Some demons love 'em.|The way they vibrate makes the skin twitch.
{21225}{21275}That the kinda demon you are, love?
{21275}{21375}I'm not a demon. I don't know why|you can hit me, but I'm not a demon.
{21400}{21475}Oh.
{21475}{21550}I see. That why you took this job?
{21550}{21650}Prove something to yourself?|A normal job for a normal girl?
{21675}{21725}Good way to drive yourself crazy, that is.
{21725}{21825}I'll be fine.
{21825}{21925}Buffy.
{21925}{22000}You're not happy here.
{22000}{22075}Please don't make this harder.
{22075}{22125}You don't belong here.
{22125}{22225}You're something...You're better than this.
{22225}{22325}- I need the money.|- I can get money.
{22350}{22375}Walk with me now, come on.
{22375}{22475}I...I need to go help Gay with the fries.
{22475}{22575}You gotta get outta here.|This place'll do stuff to you.
{22600}{22700}This place'll kill you!
{22875}{22950}Someone there?
{22950}{23050}Oh, hi. What are you doing? What...what?
{23250}{23350}Feels like I just left, you know?
{23400}{23475}You came back.
{23475}{23575}I came back.
{23750}{23800}- Gay's gone.|- Gay?
{23800}{23900}- The guy that helped me out yesterday?|- He didn't show up this morning.
{23925}{24000}Well, shifùs just starting.
{24000}{24075}He was supposed to unlock|early this morning. Didn't show.
{24075}{24150}Pull his card.
{24150}{24250}Well, I'm sure, you know, he's just late.|He didn't seem like he was leaving.
{24250}{24350}I'm moving Timothy to counter.|You're on grill.
{24350}{24425}- Me?|- I've been watching you.
{24425}{24475}But I don't know how to grill.
{24475}{24575}Just think, this is the last day|you'll ever be able to say that.
{24700}{24775}You put the beef on the grill,|hit the button, then it beeps.
{24775}{24875}You flip the beef, hit the other button,|then it beeps.
{24875}{24925}You put it on the bun...
{24925}{25000}There's not a button for that.
{25000}{25100}Repeat until insane.
{25100}{25175}It eliminates variation.
{25175}{25275}Evey burger at every|Double Meat Palace is the same.
{25275}{25350}People don't like variation.
{25350}{25450}Got it. Variety is the spice of bad.
{25500}{25600}So...whaùs the secret ingredient?
{25600}{25675}Iùs a meat process.
{25675}{25775}- Well, what does that mean?|- Iùs a process. They do it to the meat.
{25800}{25900}- But what is it?|- Iùs just the name of the process.
{25900}{26000}Oh. Yeah.
{26075}{26175}So I guess we're gonna get|kinda greasy, huh?
{26200}{26300}Skin, hair,
{26325}{26375}eyelashes,
{26375}{26450}nostrils.
{26450}{26550}Inside your ears.
{26550}{26650}You wanna look inside my ears?
{26650}{26725}No. No, thaùs OK.
{26725}{26825}Once I noticed I couldn't hear|and went to the doctor.
{26825}{26925}He said it was grease that made a plug.
{27000}{27075}I got me a kit. A kit for cleaning my ears.
{27075}{27175}Iùs got this little bulb mechanism.
{27175}{27250}Imagine that.
{27250}{27300}Buffy?
{27300}{27375}Yay! Iùs Manny!
{27375}{27450}- You're working a double shift.|- What?
{27450}{27550}Another eight hours|right after these eight hours?
{27550}{27625}But thaùs...so many hours.
{27625}{27725}You get paid for it.|Plus an extra free Double Meat Medley.
{27725}{27800}What happened? Why the double shiftiness?
{27800}{27875}Gay didn't show.|And now one of my grinder guys is late too.
{27875}{27975}But they could still show up, right?|I mean, they could be anywhere.
{28050}{28100}Your meaùs here.
{28100}{28150}Yeah, OK. Bye.
{28150}{28250}An, that was Buffy.|She's working late, so I might have to go...
{28250}{28350}I have been called|and vengeance shall I wreak.
{28350}{28450}Cower, masculine one.|Tremble as you face my wrath.
{28475}{28550}I'm starting to think|we should do a potluck thing.
{28550}{28625}Honey.
{28625}{28725}Hello. I am here to tear this man apart.|How many pieces do you wish?
{28775}{28850}- Halfrek!|- Anyanka?
{28850}{28900}Oh, my God! Hey!
{28900}{28975}How are you? How are you?
{28975}{29050}You two, you know each other?
{29050}{29150}I didn't summon you to kill Xander.|I called to invite you to our wedding.
{29175}{29200}Oh, my...
{29200}{29250}What an embarrassing mistake!
{29250}{29350}Oh, my God! Gorgeous!
{29350}{29375}Wow.
{29375}{29475}You two clearly have some catching up to do,|so I'Il...I'll not be in the apartment.
{29650}{29750}Iùs swell to see you again. I didn't mean|to have you materialise all the way here.
{29750}{29850}- Not until the ceremony, I mean.|- I guess I got the message garbled.
{29850}{29950}You know how it is. Half the time|I have no idea if I'm maiming the right guy.
{29975}{30075}So, um...you're marrying that man|with the large upper arms?
{30100}{30175}- Yes.|- Why?
{30175}{30250}Well, because I love him.
{30250}{30350}We're gonna be very happy together.
{30350}{30450}What?
{30600}{30700}Iùs boiling with nothing in it.|Sometimes it does that.
{30700}{30800}They say bugs fall in there.
{30800}{30900}Oh, I'm back. You can go on your break now.
{31450}{31525}Come in.
{31525}{31625}Iùs me. Dawn said I could come up.
{31625}{31725}So, is she pissed at you too or just at me?
{31725}{31825}What did you tell her about me?
{31850}{31950}D'you want something?
{31975}{32075}Yeah, actually. I mean,|I don't know if you wanted to keep it or...
{32125}{32175}You want it? Really?
{32175}{32275}Well, yeah, you know.|I mean, iùs not much, but iùs home.
{32300}{32350}Or it was.
{32350}{32450}- I don't know. I guess iùs stupid, but...|- No, iùs not stupid.
{32450}{32550}You can have it, of course.
{32550}{32650}Hey. So I hear you got|this whole cold turkey thing going on.
{32675}{32750}- How's that going?|- Iùs good. Iùs really good.
{32750}{32850}I mean, it was hard at first.|Frustrating doing everything the slow way.
{32900}{33000}It was like "Is everything|gonna take for ever, for ever?"
{33025}{33050}Yeah.
{33050}{33150}But iùs better now. I'm getting my focus back.
{33225}{33300}I can see that.
{33300}{33400}Iùs a pivotal page.
{33425}{33525}So this is it, huh?|This is gonna be your life from now on?
{33575}{33625}What?
{33625}{33650}No.
{33650}{33750}Well, you're never gonna do it again. Ever.
{33750}{33850}You're never gonna...|feel how it made you feel.
{33900}{33950}Don't think thaùs the way to look at it.
{33950}{34025}Hey, Will.
{34025}{34100}Iùs your birthday.
{34100}{34200}No, it isn't. But now that you mention it,|Buffy's is coming...
{34200}{34300}Potestas.
{34350}{34450}What?
{34650}{34700}Amy...
{34700}{34775}Iùs a gift. Iùs magic.
{34775}{34850}And it didn't come from you.|It came from me.
{34850}{34925}Completely legal.
{34925}{35025}Enjoy.
{35925}{36025}- Look what I found under the meat grinder!|- Oh, my God.
{36025}{36100}- Wanna tell me whaùs going on?|- I'm not sure.
{36100}{36150}Try again!
{36150}{36250}Well, there was an accident, maybe,|six weeks ago. A grinder incident.
{36250}{36325}Right, but this isn't six weeks old.|This is new.
{36325}{36425}It is? Oh, well, maybe Gay did|come in this morning or late last night.
{36450}{36525}Maybe there was an accident|and he got himself to the hospital.
{36525}{36600}Right. Maybe he's in the hospital.
{36600}{36675}Or maybe he's in the grinder! Huh? Huh?
{36675}{36700}Meat process? Secret ingredient?
{36700}{36800}Maybe Gay's on the grill!|Or maybe he's under the pickle chips!
{36825}{36925}Buffy. Buffy!
{36925}{37000}Stop! Stop! Everybody, you have to stop!
{37000}{37075}Stop eating. No, you can't eat it!
{37075}{37175}Iùs not beef. Iùs people!|The Double Meat Medley is people!
{37175}{37250}The meat layer is definitely people!|Iùs people!
{37250}{37350}Probably not the chickeny part.|But who knows? Who knows?
{37350}{37450}What about the cherry pie?
{37550}{37650}What are you doing?|I thought you were part of the team!
{37750}{37850}You are fired.
{37925}{38000}Tell me more about Xander.
{38000}{38100}You keep asking about him.|Do you think I'm making a mistake?
{38100}{38175}- Do you?|- No!
{38175}{38250}Xander, he...
{38250}{38325}He's very kind and brave.
{38325}{38425}And he has the sweetest smile|and the nicest body, and he loves me.
{38425}{38475}Sometimes it isn't easy, but he does.
{38475}{38575}Who told you that it isn't easy to love you?
{38575}{38675}Well, I'll do something or say something
{38700}{38800}and then he has to say stuff like "Iùs incorrect|for you to appreciate money so much"
{38800}{38875}or "Observe. here is how|a real human would behave."
{38875}{38975}Oh, so he corrects you?
{38975}{39050}Well, no, iùs just...
{39050}{39150}Well, now I'm all confused. You think there's|something wrong with the way he treats me?
{39200}{39225}Do you?
{39225}{39300}OK, you have to stop doing that.|I love Xander.
{39300}{39350}Even though he thinks he knows better?
{39350}{39450}- But he doesn't. He doesn't think that.|- OK. I'm sorry. I was just curious.
{39475}{39575}You don't have to say another thing about it|if you're not comfortable.
{39600}{39700}But I am! I mean, iùs not like|I'm hiding any deficiencies or anything.
{39825}{39875}I have absolutely no threes.
{39875}{39975}Go fish.
{39975}{40075}I call an emergency meeting, and this is it?|Where's Willow? Anya?
{40075}{40150}I couldn't find Willow.|I knocked and knocked on her door.
{40150}{40225}Anya's entertaining|a vengeance demon named Hallie.
{40225}{40325}Say, Buff, did you ever see Anya as a demon?|Cos if thaùs it, whoa.
{40325}{40425}There's something wrong|at the Double Meat Palace. Really wrong.
{40425}{40500}Have you been demon- fighting?|Is that why you smell funny?
{40500}{40600}No! I'm talking about...
{40600}{40675}Thaùs great. Thaùs just great.
{40675}{40775}I try to get an ordinary job in a well- lit place|and, look, I'm right back where I started.
{40800}{40875}Blood and death and funky smells.
{40875}{40975}Look. Look what I found near the grinder.
{41025}{41100}- Whose is that?|- I don't know.
{41100}{41200}It might be this guy named Gay,|the only one who didn't seem all braindead.
{41200}{41300}He didn't show up this morning. Except now|I think he was there as the secret ingredient.
{41325}{41425}We need to analyse that burger.|We need to find out if it used to be people.
{41425}{41475}What?
{41475}{41575}- People?|- Xander, you ate the burger?
{41575}{41675}First you say iùs cat, then you come in,|hand me a burger, blah blah blah.
{41675}{41775}Five minutes later "And by the way|it happens to be hot, delicious human flesh"!
{41775}{41875}I needed that burger to analyse it.|Now I'm gonna have to get another one.
{41875}{41975}Thaùs your problem with this scenario?|You getting seconds?
{41975}{42075}Late! Late. Sorry. I was reading for school.|Well, highlighting anyway. Anyway, late.
{42150}{42200}Yeah, you just missed the Gay burger.
{42200}{42300}What are we doing? Leùs jump right in.|Did Xander say something about food?
{42400}{42500}You wouldn't want any. Apparently,|the Double Meat Medley is people.
{42550}{42600}Whoa. Bad.
{42600}{42650}I bet iùs not even just this one time.
{42650}{42750}Or even this one town. There are|Double Meat Palaces all over California.
{42750}{42800}- I've eaten there a lot.|- Everyone has.
{42800}{42900}They've got the perfect deal -|everyone expects high turnover of workers.
{42900}{43000}They get the meat for nothing and they have|us disposing of the bodies. How sick is that?
{43050}{43125}We need to bring down|the whole corporation.
{43125}{43225}Will! Xander ate the burger. Is there|any way for sure to figure out what it was?
{43225}{43325}Yeah, I can start analysing it with science.|Not...I can use science.
{43350}{43375}You ate it?
{43375}{43475}We have the wrapper. There's little|scribbles of meat on the wrapper.
{43500}{43575}You work on that. Iùs after closing,|so I'm gonna go see what I can find out.
{43575}{43675}Cool. You go. We'll be good.
{43800}{43825}Are you OK?
{43825}{43925}I'm just worried about Buffy.|She could be walking into anything.
{45000}{45100}Manny?
{45275}{45375}Manny?
{45375}{45475}Guess you really were a lifer.
{45525}{45625}Don't need magic.|Don't need it. Don't need it.
{45625}{45725}My friend Janice - her sister's a lawyer.
{45750}{45850}You think I should Sue over the burger?|Thaùs interesting.
{45850}{45925}No, I just mean...
{45925}{46025}Buffy's never gonna be|a lawyer or a doctor, anything big.
{46050}{46150}She's a Slayer. She saves the whole world.|Thaùs way bigger.
{46150}{46250}But that means she's gonna have crap jobs|her whole life, right? Minimum- wage stuff.
{46275}{46350}I could still grow up to be anything.
{46350}{46425}But for her...this is it.
{46425}{46525}OK, but maybe you'll be a lawyer or a doctor,|and you can support your deadbeat sister.
{46575}{46650}Oh, thaùs terrifically better. Thanks.
{46650}{46750}- Hey, guys, I think I've got it.|- Good job, Will.
{46750}{46825}- Those aren't, like, potions, are they?|- No. No potions.
{46825}{46925}Iùs not magic. Iùs chemistry.|You can tell by how damn slow it is.
{46975}{47075}I made a solution that reacts|to the proteins in human blood.
{47075}{47175}So we're pretty close to knowing for certain.
{47175}{47250}I'm here. I'm here.
{47250}{47350}- We're doing chemistry.|- Oh. So sorry I hurried.
{47350}{47425}Did your friend have a good time,|and then leave?
{47425}{47475}She's gone.
{47475}{47575}So, An, the way she looked, with...the face...
{47575}{47625}That wasn't what|you used to look like, was it?
{47625}{47725}Something wrong with that?|Did you think she was unattractive?
{47725}{47800}Is there any answer to that question|that won't make you nuts?
{47800}{47875}Halfrek was always considered|to be a great beauty.
{47875}{47925}Well, hon, she was a little...
{47925}{47975}There was some veininess.
{47975}{48025}Hold this.
{48025}{48125}OK. If the solution reacts to the proteins,|then I'll be able to see it.
{48150}{48250}I mean, I'll be able to look through|the microscope and then see it.
{48275}{48325}You're not so perfect either,
{48325}{48425}what with your strangely large upper arms|and your tendency to criticise.
{48450}{48500}Huh?
{48500}{48575}- What do you see?|- There's no reaction.
{48575}{48625}Oh, God, no! There's no reaction.
{48625}{48725}- Which means iùs not human.|- Iùs not human!
{48750}{48825}- Iùs not human?|- Well, is it demon meat?
{48825}{48925}I mean, maybe someone's killing demons|and using them as a cheap source of meat.
{48950}{49000}We've all heard of that.
{49000}{49100}I'm opposed to using demon meat, no matter|how much money it saves. Surprise you?
{49100}{49150}Again, I say "Huh?"
{49150}{49250}No, I'm not sure what I'm seeing. Cellulose?
{49300}{49400}There's something weird here.
{49675}{49775}Scalp?
{49800}{49825}Wig!
{49825}{49875}Wig lady?
{49875}{49925}Oh, dear.
{49925}{50025}"Wig lady." Is that what they call me?
{50050}{50125}I don't care for that.
{50125}{50225}I mean, I have to do something to hide this.
{50375}{50475}Iùs paralysing. Don't try to move, dear.|You really can't, much.
{50825}{50900}The paralysis spreads upward, by the way.
{50900}{51000}You may want to flail your arms a bit|while you still can.
{51025}{51125}Did I tell you? You're my favourite.
{51150}{51200}Double Meat workers.
{51200}{51300}You're so full of Double Meat burgers|and you just slide down so smooth.
{51400}{51450}Oh, I just love the paralysis.
{51450}{51550}It means I can eat you slowly.
{52025}{52125}I know you're under there.
{52150}{52250}Buffy? Are you in there?|I can't see you inside.
{52275}{52375}Buffy, if you're in there,|the burger isn't people.
{52475}{52575}They aren't even meat. Iùs all|processed vegetables. Isn't that weird?
{52650}{52750}Buffy, there's more.|Something happened today.
{52775}{52875}It wasn't my fault. It was Amy's fault,|but I feel so bad about it.
{52900}{53000}It was Amy's power, but it felt like I was|doing everything myself. And I couldn't stop.
{53050}{53150}And now iùs gone and I feel kinda shaky|and...like I need it, Buffy.
{53525}{53625}Buffy, something fell.
{53750}{53800}Buffy!
{53800}{53900}Visitors. How nice.
{54050}{54150}Missed me.
{54250}{54350}Buffy!
{54600}{54650}Buffy, are you all right?
{54650}{54725}Paralysed, but...I think iùs wearing off.
{54725}{54825}I did it! I killed her, Buffy. Look!
{55225}{55275}Hey.
{55275}{55350}Amy.
{55350}{55425}Can I come in? My new place isn't set up|and I wanted to borrow detergent.
{55425}{55500}You really can't.
{55500}{55550}I can't borrow detergent?
{55550}{55650}When they call me Stinky Amy|I'm just gonna say "Not my fault."
{55650}{55725}I can't spend time with you any more.
{55725}{55800}- What?|- You can't come in here again.
{55800}{55875}Whaùs up? You didn't like|your birthday present?
{55875}{55925}Thaùs right.
{55925}{56025}You're telling me that|you didn't have a genuine blast?
{56025}{56125}Come on, that was a sweet spell. It was|like a trip to Disneyland without the lines.
{56150}{56250}You don't get it.|What you did to me was wrong.
{56250}{56350}Do you have any idea how much harder|that makes just everything?
{56350}{56450}You know what I notice?|You're not denying that you had fun.
{56450}{56500}- Shut up.|- Oh, yeah.
{56500}{56600}Sharp argument you got there.|Were you on the debate team? I forget.
{56625}{56725}I forgot a lot while you were|failing to make me be not a rat.
{56725}{56825}Amy, if you really are my friend,|you better stay away from me.
{56875}{56975}And if you really aren't...|you better stay away from me.
{57475}{57525}Yeah?
{57525}{57625}Hi. You must be the new manager.|I'm Buffy Summers.
{57625}{57725}I'm Lorraine Ross. They called me in|when Manny did his disappearing act.
{57725}{57800}You hear about that? Guy just disappeared.
{57800}{57900}Yeah. I think...I think|that used to happen a lot around here.
{57900}{57975}Wait. Buffy Summers?
{57975}{58050}I heard about you. Caused a big scene.
{58050}{58100}Oh, yeah.
{58100}{58200}Practical jokes not really right for|the workplace. I so get that now.
{58225}{58300}Anyway, I just wanted to return my uniform.
{58300}{58400}Most people don't even bother.
{58475}{58575}The Double Meat Medley...is vegetables?
{58600}{58650}How do you know that?
{58650}{58700}So I guess iùs true.
{58700}{58800}Um, close the door?
{58825}{58925}Have a seat.
{58975}{59075}Iùs a texturised, vegetable- based,|meat- like product, suitable for grinding.
{59100}{59175}Iùs blended with large amounts|of rendered beef fat for flavour.
{59175}{59275}The secret ingredient|in the beef is beef?
{59275}{59375}Buffy, you know something powerful here.|Do you understand that?
{59375}{59475}The Double Meat reputation|is built on a foundation of, well, meat.
{59500}{59550}You can't spread this around.
{59550}{59650}I get that.
{59650}{59750}- Iùs a valuable secret, isn't it?|- Is there something you want?
{59800}{59875}- I really need money.|- You want money?
{59875}{59975}No! Well, I mean, yes,|but, no, I...I want to work.
{60025}{60100}See, I have zero money coming in,|and there are expenses.
{60100}{60200}And by the time I interview for a new job|and go through a training process...
{60200}{60300}I'd...I'd really like to not be fired any more.
{60325}{60400}I don't want any more practical jokes.|I mean it.
{60400}{60475}I promise.
{60475}{60575}Well, I'm a little short- handed right now|and you're already trained.
{60625}{60675}I think you can not be fired.
{60675}{60775}Thank you. Thaùs great.|I can do the job. I promise that, too.
{60800}{60850}I certainly hope so.
{60850}{60950}I don't like short- timers, Buffy.|I like people who want to be here.
{60975}{61075}Maybe you didn't take this job seriously|before, but from now on...See this?
{61150}{61225}I want you to be shooting for this|from here on out.
{61225}{61325}Right. Here on out.